raspibolt/raspibolt_61_system-overview.md

It doesn't come pre-installed:
```
/usr/local/bin/raspibolt: 57: /usr/local/bin/raspibolt: jq: not found
/usr/local/bin/raspibolt: 63: /usr/local/bin/raspibolt: jq: not found
expr: syntax error
/usr/local/bin/raspibolt: 66: /usr/local/bin/raspibolt: jq: not found
/usr/local/bin/raspibolt: 69: [: -eq: unexpected operator
/usr/local/bin/raspibolt: 73: [: -eq: unexpected operator
/usr/local/bin/raspibolt: 77: [: -le: unexpected operator
/usr/local/bin/raspibolt: 94: /usr/local/bin/raspibolt: jq: not found
/usr/local/bin/raspibolt: 105: [: =: unexpected operator
/usr/local/bin/raspibolt: 112: /usr/local/bin/raspibolt: jq: not found
```

Add jq install instructions to system overview guide

---

raspibolt/raspibolt_20_pi.md

This makes the guide work with a macOS source machine.

Add steps to use with HFS+ formatted hard drive

---

raspibolt/raspibolt_30_bitcoin.md

i needed to add the `-daemon` flag to make the systemd job not hang and crash. Also added the `-conf` flag for more precise. Was there a reason you omitted these? If no, here is a pull-req.
might it also be good idea to add the hardening configs as suggested in official [bitcoin systemd file](https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service#L23-L41) ?

added flags to systemd bitcoind.service file

---

raspibolt/raspibolt_20_pi.md

I was getting this error at the swapon step. Manually creating the swapfile seemed to work. For reference see https://www.raspberrypi.org/forums/viewtopic.php?p=251251.
This fixes #105.

Fix `swapon: /mnt/hdd/swapfile: read swap header failed`

---

raspibolt/resources/lnchannels

Enhancement to lnchannels to show if a node is not responding if a channel is inactive
In this example:
*  Channels to KRYPTO.KOELN are inactive, but the node seems active
*  Channels to _poole_party_ and _Stadicus RaspiBolt_ are inactive, and the nodes seem down (?)

Add check to see if IP:PORT is open for inactive channels

---

raspibolt/raspibolt_20_pi.md

Solution to issue #130 where the swapfile could not be deleted via
`$ sudo rm /var/swap`
which resulted in
`> rm: cannot remove '/var/swap': Operation not permitted`

$ sudo rm /var/swap #130

---

raspibolt/raspibolt_30_bitcoin.md
raspibolt/raspibolt_faq.md

The latest RPis are running a 32 bit operating system even though they have 64 bit processors. This tripped me up for a moment when downloading the latest version of Bitcoin and may be valuable information for anyone who is not experienced with Raspberry Pi.

Add information on 32 bit Bitcoin version download

---

thundroid/README.md

`shutdown -r now` not `restart shutdown -r now` after setting new swap file.

restart typo removed

---

raspibolt/raspibolt_30_bitcoin.md

`lnd` now needs distinct ports for `zmqpubrawblock` and `zmqpubrawtx` so just use the defaults

Distinct ports for zmqpubrawblock, zmqpubrawtx

---

raspibolt/raspibolt_69_lncli-web.md

Added a few lines to choose the right folder to copy the admin.macaroon from. The location where admin.macaroon is created changed since LND-0.5. If you run this tutorial for the first time, it will now be compatible with LND-0.5.

update lncli-web macaroon folders

---

raspibolt/raspibolt_40_lnd.md

As https://testnet.manu.backend.hamburg/faucet has been abandoned and no testnet coins are available from this faucet anymore, here is a new one: https://testnet-faucet.mempool.co

Update testnet faucet link

---

raspibolt/resources/20-raspibolt-welcome

With LND 0.5 the macaroon location was moved. This commit fixes the location and is variable based on whether testnet is being used.

Fix for the LND 0.5 break

---

raspibolt/raspibolt_40_lnd.md

One of the items to be removed when running this command is the bitcoin download directory. Since it's a directory, we should specify `-rf` when running `rm`.

Include -rf when clearing admin download dir

---

raspibolt/raspibolt_20_pi.md

Added `-S` flag to the command to copy over your public key to the Raspberry Pi and set the file mode of the .ssh directory.
Reason:
Without the `-S` flag this issue comes up:
`sudo: no tty present and no askpass program specified`
The `-S` flag directs sudo to read the password from the standard input, stdin.
Source: https://askubuntu.com/questions/281742/sudo-no-tty-present-and-no-askpass-program-specified/724384#724384

Added `-S` flag to copy pub key to raspi

---

raspibolt/raspibolt_40_lnd.md

After stopping LND to set up LND autostart, it has to be unlocked again to use `sudo journalctl -f -u lnd`

Added unlock after starting LND again

---

raspibolt/raspibolt_40_lnd.md

This PR swaps out the `lnd` version to be installed from `..0.5-beta` to `..0.5.2-beta` to include newest changes and bugfixes. The respective changelogs for the new versions can be found at:
- [lnd v0.5.1-beta release](https://github.com/lightningnetwork/lnd/releases/tag/v0.5.1-beta)
- [lnd v0.5.2-beta release](https://github.com/lightningnetwork/lnd/releases/tag/v0.5.2-beta)
No material changes are made to the rest of the install process as far as I can tell by using this newer version. I just updated my node from `0.5` to `0.5.2` and it came back up with all balances and channels intact.

Update `lnd` install version

---

raspibolt/resources/20-raspibolt-welcome

This bug only became apparent when the free space on / fell below 1GB on my SD card
The change is explained by an example
```
$ df -h
/dev/root        14G  8.4G  4.0G  68% /
```
Calculated free space by orig file: 29% = OK
```
$ df -h
/dev/root        14G  8.4G  300M  68% /
```
Calculated free space by orig file: 2143% = Bad
```
$ df
/dev/root       13671000   8799372   300000  68% /
```
Calculated free space by new file: 22% = Good

Simple Bug Fix on % free storage

---

raspibolt/resources/20-raspibolt-welcome

CHANGE 1
Cleaned up the repeated instances of "/usr/local/bin/lncli --macaroonpath=${macaroon_path} --tlscertpath=${lnd_dir}/tls.cert"
CHANGE 2
Added in/out channels on bitcoind (As requested here: Stadicus#370)
CHANGE 3
Added balance locked in Pending Channels.
The importance of this is recognised by anyone that has had to do a lncli closechannel --force. The channel's csv_delay value may cause the pending balance to be locked up for a period of 1 week (or more). Seeing the funds are 'pending' is a bit less likely to cause panic.
CHANGE 4
Added a grand total of sats in 
* wallet
* channels
* pending on-chain transactions

Add bitcoind channels, lnd pending/total sats

---

raspibolt/raspibolt_64_electrum.md

There was 2 packages that the latest version of Electrum Personal Server (v0.1.6) required and were not included in the instructions: `setuptools` and `wheel`. I found this to be a problem for some people according to issues in GitHub or comments on Reddit/forums.
I edited the guide according to the steps I followed and worked in my Raspberry (Raspbian). However, there might be a better way to structure those changes.

Install additional required Python packages

---

raspibolt_72_zeus-over-tor.md

Based on this guide: https://github.com/openoms/bitcoin-tutorials/blob/master/Zeus_to_RaspiBlitz_through_Tor.md
With this setup, I'm able to connect to my Thundroid node over tor using the Zeus android app. Can probably be tweaked to also work with Shango Wallet.

Guide: Connect Zeus App To RaspiBolt Over Tor

---

raspibolt_64_electrum.md

Changes the documentation to install Electrum Personal Server version 0.1.7. Also Chris Belcher's public key has changed location and is reflected with thir PR.
It overrides the image "Install Electrum Personal Server with Python Pip" using a temporary image. Please add image to `images/60_eps_pip_install.png` or change it accordingly. This PR does not update the image found in `images/60_eps_electrum-connect.png`.

Updates to Electrum Personal Server 0.1.7

---

resources/20-raspibolt-welcome

When checking to see what port bitcoind is using in bitcoin.conf, this script currently greps for the port number like so:
```
cat ${bitcoin_dir}/bitcoin.conf 2>/dev/null | grep port= | awk -F"=" '{print $2}'
```
However, this would mean that it would pick up the port number for the `rpcport=` from bitcoin.conf (even if it was commented out), such as:
```
#rpcport=8332
```
As a result, this script would end up checking to see if the node is publicly available by doing `nc -z {ip} 8332`, even if the node was running on port 8333 like normal.
So all I've done is make a tiny edit to the grep to only look for lines that start with `port=` only, which avoids accidentally grabbing the wrong port number from lines like `rpcport=` or even `#port=`:
```
cat ${bitcoin_dir}/bitcoin.conf 2>/dev/null …
```

Grep for "^port=" in bitcoin.conf

---

raspibolt_20_pi.md

Changes [redundant](https://en.wikipedia.org/wiki/RAS_syndrome) usage of _local **L**ocal **A**rea **N**etwork_ to just _**L**ocal **A**rea **N**etwork_.

Improve wording in UFW setup

---

raspibolt_50_electrs.md

Fixes minor typos in the commands to install `electrs`.

Electrs: typos in commands

---

raspibolt_10_preparations.md
raspibolt_20_pi.md
raspibolt_21_security.md
raspibolt_30_bitcoin.md
raspibolt_40_lnd.md
raspibolt_50_electrs.md
raspibolt_60_bonus.md
raspibolt_65_system-recovery.md
raspibolt_70_troubleshooting.md

**Consistent usage of /usr/local/bin**
While `/usr/bin` is for distribution-managed user programs, `/usr/local/bin` is for user programs that are not managed by the package manager. All manually installed binaries like `bitcoind`, `lnd` and `electrs` should be in `/usr/local/bin.`
* updates installation instructions
* adjusts systemd unit files
**Wording and consistency**
Small typos, inconsistencies and other nits I stumbled upon proof reading.

Minor fixes

---

raspibolt_40_lnd.md

Guess this was just missed in #507. Noticed when upgrading LND on my RaspiBolt.

Correct `lnd --version` example output for 0.8.2

---

raspibolt_50_electrs.md

Typo in config: using dash (command line style) instead of underscore (config style)

Correct electrum rpc address setting in electrs config

---

raspibolt_50_electrs.md

fixes https://github.com/Stadicus/RaspiBolt/issues/516
This commit fixes a copy/paste error from the BitBoxBase project.

fix electrs.service

---

raspibolt_30_bitcoin.md

related to https://github.com/Stadicus/RaspiBolt/issues/515
To force bitcoind to not accept clearnet connections, even when
initiated from the outside (e.g. other bitcoin nodes remembering
the clearnet ip address), `bind=127.0.0.1` is added to
`bitcoin.conf`

Bind bitcoind to localhost

---

raspibolt_22_privacy.md
raspibolt_69_tor.md

Hi,
I suggest to replace `usermod` with `adduser` to add users to groups, since `adduser` is more user friendly and it is already used in other places (e.g. `raspibolt_20_pi.md`).

Replace usermod with adduser

---

raspibolt_20_pi.md
raspibolt_22_privacy.md
raspibolt_30_bitcoin.md
raspibolt_40_lnd.md
raspibolt_50_electrs.md
raspibolt_61_system-overview.md
raspibolt_62_commandline.md
raspibolt_64_electrum.md
raspibolt_66_remote_lncli.md

Hi,
Rouge library (a library used by Jekyll for syntax highlighting) has options to highlight config snippets.
I added `conf`, `ini` language specifications for snippets with configurations. Also I added `sh` language specification where it was missed.

Use conf syntax highlighting

---

raspibolt_30_bitcoin.md

Hi,
Bitcoin Core has an option to disable the node to listen to and relay transaction.
I set it as an optimization for initial block download.

Set blocksonly=1 to speed up IBD

---

raspibolt_60_bonus.md
raspibolt_75_trezor-agent.md

I rewrote the HW SSH guide using trezor-agent as a bonus guide.
I wrote the guide for the Trezor because I was able to successfully test on it but Ledger and Keepkey should work as well

SSH to your raspibolt using Trezor hardware wallet

---

raspibolt_6B_btc_rpc_explorer.md

I feel a bit uncomfortable to run `BTC RPC Explorer` (with 28 direct dependencies) alongsite `bictoind` and `lnd` (with private keys).
To mitigate some risks I propose to run `BTC RPC Explorer` as a separate user.

Run BTC RPC Explorer as another user

---

raspibolt_50_electrs.md

Since `nginx` is configured with SSL, `s` should be used when connecting from Electrum.

Fix protocol to connect from Electrum

---

raspibolt_40_lnd.md

LND 0.9.1 is no good for the RaspiBolt.
As described in issue #576

Update to LND 0.9.2 . Fixes issue #576

---

raspibolt_50_electrs.md

Remove deprecated TLS versions 1.0 and 1.1.
See https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.0.

Remove deprecated TLS versions

---

raspibolt_21_security.md

Setup SSH keys access before enabling `fail2ban` to avoid locking yourself. (That is what I did :).
If it is merged I would like to propose to copy keys with `ssh-copy-id` command which deals with folder creation and keys transmission.

Setup SSH keys before fail2ban

---

raspibolt_20_pi.md
raspibolt_22_privacy.md
raspibolt_30_bitcoin.md
raspibolt_50_electrs.md
raspibolt_6B_btc_rpc_explorer.md

* bitcoind: txindex=1 by default
With the performance of RPi4, enabling txindex is not a big deal. To support later addition of services like blockexplorer etc, this setting is enabled by default.
Added explanation what it is and how to disable it.
* explain errors after raspi-conf 
The 'hostname' and 'locale' errors look quite scary, although they are not critical. This is explained, with optional steps to get rid of the 'locale' error.
* minor improvements
* formatting
* Pi: reboot instead of shutdown
* Privacy: streamline adding 'bitcoin' to 'debian-tor' group
* Electrs: update to Rust 1.41

Minor updates

---

raspibolt_55_explorer.md
raspibolt_60_bonus.md

The personal block explorer has become an indispensable privacy tool.
Ofter several minor fixes, the bonus guide is clear enough to be part
of the main RaspiBolt guide.
This pull request
* moves the bonus section into the main guide
* adds update instructions for Electrs

Move BTC RPC Explorer to main guide

---

raspibolt_20_pi.md
raspibolt_69_tor.md

sudo apt full-upgrade should be better due to the fact that it should install new packages if necessary to satisfy dependencies of upgrading already installed packages.

Replacing apt upgrade with apt full-upgrade, fixing locale error and notice Bitnode not connectable

---

raspibolt_61_system-overview.md

The location `/home/admin/download/` isn't guaranteed to exist, but /tmp is. 
Since the script is moved anyways, there's no reason to enforce existence of a download folder.

Update raspibolt_61_system-overview.md to use /tmp

---

raspibolt_40_lnd.md

Release notes on LND v0.10.2-beta indicates support for bitcoind 0.20, which is referenced in raspibolt_30_bitcoin.md

Update raspibolt_40_lnd.md to use LND v0.10.3-beta

---

raspibolt_10_preparations.md

Reference https://github.com/Stadicus/RaspiBolt/issues/599 regarding 500GB not being large enough for full blockchain and electrs database before compaction.

Update disk size recommendations

---

raspibolt_50_electrs.md

- Rust updated to 1.44.1
- Electrs updated to 0.8.5
- No prompt install clang cmake
- Update sample outputs (slower hard drive, version)

Update raspibolt_50_electrs.md for newer versions

---

raspibolt_40_lnd.md

The v0.10.4-beta release of LND on 2020-07-15 mainly addresses a Windows file handle issue but its best to stay in lockstep with the latest versions.  This will also resolve the System Overview showing the user to "Update!".

Update raspibolt_40_lnd.md to lnd v0.10.4-beta

---

raspibolt_40_lnd.md

roasbeef's key now is secondary, see https://github.com/lightningnetwork/lnd/releases/tag/v0.11.1-beta
Verify both signatures.

There is a new primary release signing key for LND v0.11.1

---

raspibolt_50_electrs.md
raspibolt_faq.md

Primary install now dynamically determines latest release version from repository tags
FAQ now includes a section on how to upgrade Electrs. Note that each version backup is about 350-400 MB.

Electrs update to newest version

---

raspibolt_50_electrs.md

Adresses this comment from Kixunil:
> Also we had an issue recently that someone installed Rust using your
> guide on x86_64, which broke the system. Perhaps an explicit warning
> that the guide will only work on RPi would be useful?

Rust: add warning for ARM32 binaries

---

raspibolt_40_lnd.md

Parameter `-o` (lowercase) redirects the log output into a file, while `-O` (uppercase) stores the document to the file (what is wanted here).

Small fixes

---

raspibolt_30_bitcoin.md

Bitcoin Core 0.21.1 was released!
Release mail: https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2021-May/000099.html

Upgrade to Bitcoin Core version v0.21.1

---

raspibolt_40_lnd.md

Enable Anchor Commitments and Wumbo Channels
See https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf for all lnd.conf options
; If set, lnd will use anchor channels by default if the remote channel party
; supports them. Note that lnd will require 1 UTXO to be reserved for this
; channel type if it is enabled.
; protocol.anchors=true
; If set, then lnd will create and accept requests for channels larger than 0.16
; BTC
; protocol.wumbo-channels=true

Enable Wumbo channels and Anchor channels for LND

---

raspibolt_6A_auto-unlock.md

This changes the recommendation to write the password and `chmod` the file afterwards to creating an empty file with correct permissions first and writing the password into it afterwards. This avoids theoretical attack of a malicious app seeing the password between writing it and protecting the file.
Note that this whole exercise, especially setting the owner as root, may be pointless because any process that can access TLS private key or run under the same user as lnd can steal password/sats no matter what kind of unlocking mechanism is used. Protecting lnd in such scenarios is physically impossible. And if you assume these scenarios will not happen, then it makes sense to assume `pwd` file will not be accessed by other user than the one running `lnd`, so in conclusion `pwd` file **may** …

Recommend creating password file BEFORE writing

---

raspibolt_55_explorer.md

This changes documentation for installation and upgrades to use the beautiful 3.x version of BTC RPC Explorer

Update BTC RPC Explorer to v3.1.0

---

index.md

Add links to the various platforms that can support Raspibolt users, _i.e._ the Github issue page and the new subreddit and Telegram group dedicated to the Raspibolt.

Add links to community platforms

---

raspibolt_faq.md

Deleting the macaroons before upgrading to a new version of LND does not seem to be required anymore (see comment by @guggero here: https://github.com/lightninglabs/lightning-terminal/issues/241#issuecomment-869848449).
Unless there is still a reason to delete all the macaroons before upgrading, it is probably safer to remove this step.

Removing the step that deletes macaroons when upgrading LND

---

raspibolt_40_lnd.md

Add a section to install LiT instead at the end of LND installation guide
Much easier to install than having to install loop and pool in standalone so it should be straightforward to review !
(please give some love to my other PR #644 too, I really have a great experience with WireGuard VPN on my RaspiBolt instead of Tor)

Add installation of LiT in Lightning section

---

raspibolt_76_specter-desktop.md

The procedure has been changed since `v1.5.0` in order to not have huge babel-mo-blob-files in the repo. Therefore these files need to be created as part of a hook of the setup-process.
In order for that hook to function properly, you have to install babel prior to that.

add i18n specific stuff

---

raspibolt_20_pi.md
raspibolt_40_lnd.md

Summary: the updates aim at:
1. using the latest lnd and litd releases,
2. correcting typos and broken links,
3. adding useful options to the lnd/litd configuration files,
4. replacing outdated commands and examples and warning for outdated videos, and;
5. adding a few safety information for some commands.
The full list of changes and rationales for them:
1. Added warning above most videos: (Warning: the video below is outdated and does not correspond exactly to the commands above)
2. Updated the 'download and install' section with latest release (v0.13.1). Removed bitconner-related lines as not used for the verification process.
3. Updated lnd.conf content 
4. Removed protocol.anchor=true (now by default) (Fixes #748 )
5. Added AMP payments options (did not add keysend as AMP renders …

Update raspibolt_40_lnd.md (many updates of the lnd/litd guide)

---

404.md

With the move to the new organization and upcoming page
reorganization, a proper 404 "page not found" error page is
helpful.
The main advantage is that it includes the navigation
sidebar, so even if a specific page is not available, visitors
can quickly find what they're looking for.

add 404 error page

---

index.md

The MD source files are not very convenient to use as an archive of older versions. The deprecated version 2 of the RaspiBolt guide is now published at https://v2.raspibolt.org, and this commit changes the link on the homepage.

add link to https://v2.raspibolt.org

---

btcrpcexplorer.md
electrs.md
privacy.md
rtl.md

There is no need to restart neither nginx nor tor on each configuration change.

Avoid unnecessary nginx / tor restarts, reload is enough

---

btcrpcexplorer.md

Because nginx reverse proxy already provides that.
Also, nowhere user is later directed to even try connecting to port 3002.

Allowing external access to BTC RPC Explorer is not needed

---

electrs.md

Users must wait until Electrs fully indexed the blockchain and compacted
its database before proceeding to configure wallets.
This was not explicitly mentioned, the added note should make that clear.

Electrs: add remark to wait until synced

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support.md
.github/pull_request_template.md

Support in issues and collaboration through pull requests was done
without proper guidance. Providing a template for both encourages
the inclusion of essential information.

add pull request and issue template

---

lnd.md

Currently, the user "admin" does not have access to the necessary files to interact with LND through `lncli`.
The user "admin" is the main administrative user and should be able to control the system. 
This change gives it access to the TLS certificates and the admin.macaroon file. This change is also a prerequisite to run the [MOTD welcome script](https://raspibolt.org/bonus/raspberry-pi/system-overview.html) without sudo privileges.
Fixes https://github.com/raspibolt/raspibolt/issues/804
Run the added commands on a RaspiBolt v3 and check if user "admin" can run `lncli getinfo` afterwards. No additional maintenance is required.

lnd: give user 'admin' access to lncli

---

bonus/lightning/lntop.md

Fixes guide for RaspiBolt v3. Changes download from armv6 to arm64<del> and adds instructions about copying necessary LND credentials</del>.
Note - there is also recent v0.2.0 release of lntop, but it does not provide precompiled binaries.

Update lntop bonus guide for RaspiBolt v3

---

rtl.md

Fixes a small typo for the NodeJS version used for RTL.
To avoid confusion for new users.
Fixed typo "12" to "14"
N/A
NodeJS version 14 is describd as "the most recent stable one". However when checking [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/) it shows v18 as "Current", v16 as the "Active LTS" and v14 and v12 as "Maintenance LTS". Wouldn't v16 be the most recent stable one? not sure how 'stable' matches the NodeJS terminology there! :)
Shoudl we reword "the most recent stable one"..?

Fixed NodeJS version typo

---

.gitattributes

This PR allows Markdown to be counted in the repo language stats
To avoid possible confusion for new users about the content of the repo.
I followed the following [guide](https://joshuatz.com/posts/2019/how-to-get-github-to-recognize-a-pure-markdown-repo/).
The language stats is done by [linguist](https://github.com/github/linguist). Mardown files are ignored by default but this can be overide by adding a `.gitattributes` file in the root folder of the repo that contains a few options.
Test: Create file in root folder of local repo. Check that the language stats now contains Markdown and is > ~90%.
Maintenance: None

Recognize Markdown as language in repo

---

btcrpcexplorer.md
preparations.md
rtl.md

Passwords used at various steps of the guide are setup at the start in the 'Preparation' section and given a letter name (A to C for now). 
An optional password is discussed for the Explorer and a compulsory password is required for RTL. These two passwords are not mentionned yet in the preparation section.
For consistency, this PR proposes to add password [D] and [E] in the preparation section for respectively the Explorer and RTL. The PR also refers to passwords [D] and [E] in the Explorer and RTL guides (as is done for passwords A to C in the other guides that use them).
Improves guide consistency. Reduce the risk of users not recording the passwords for Epxlorer and RTL in a proper way.
Added references to passwords [D] and [E]
Test: just checking that the right password letters are …

Add passwords [D] & [E] for Explorer and RTL

---

lnd.md

This PR aims at adding an optional recommendation to not only backup the LND wallet 24 mnemonic words on paper but also on steel to have a much more resilient backup. In the DIY spirit of RaspiBolt, the recommendation is to use a DIY solution with off-the-shelf items only (no bitcoin merchants used) to reduce privacy/security risks (merchant client DB leaks etc): stamped steel washers held on a bolt.
In case of node failure, the 24 words / mnemonics are indispensible to initiate a SCB recovery and recover all the user funds onchain. These words could secure a significant amount of bitcoins and therefore a resilient storage method must be recommended. The solution proposed is very aligned with the RaspiBolt ethos.
Added an extra paragraph after the paper backup paragraph that explains the …

Recommend optional DIY steel backup for LND 24 words

---

index.md

A tiny little link fix :-) 
https://raspibolt.org/bonus-section.md seems to be dead
Replacing the link and testing it through:
> `docker run --rm -it -v $(pwd):/srv/jekyll -p 4000:4000 jekyll/jekyll:pages jekyll serve --watch`
P.S: Pretty cool how the project evolved from simple markdown files, props for the work 👍

Fix: Bonus guide link

---

bonus/lightning/lntop.md

Update to latest release now that binaries are available.
Version 0.2.0 of lntop adds some new features and bugfixes:  
https://github.com/edouardparis/lntop/releases/tag/v0.2.0
This change also adds binary signature verification as best practice.
Simple update of download links, plus added instructions for checksum signature validation. See https://github.com/edouardparis/lntop/issues/49 for some context.
Deleting downloaded files is removed as these are small and the /tmp folder is purged on every reboot anyway.
Follow instructions and run `lntop`

lntop: update to v0.2.0

---

btcrpcexplorer.md
electrs.md
rtl.md

This change fixes a few minor errors in for Electrs, RTL, and BTC RPC Explorer:
* copy/paste errors in NGINX config
* wrong link to upgrade repository
* use 'git describe --tags --abbrev=0' to get the most current tag (see [documentation](https://git-scm.com/docs/git-describe#Documentation/git-describe.txt---abbrevltngt))
Consitency and accuracy
Just some wording changes
wording only, might run `git describe` command

minor fixes: Electrs, RTL, BTC RPC Explorer

---

bonus/lightning/lntop.md

This PR adds a section to the lntop bonus guide that explains how to use it (what keys to use and how to navigate the displays).
The navigation is not necessarily easy to work out and the explanations are a bit hard to find! Laying out clear instructions would help users to make the most of lntop :)
Used the 'keybindings.go' file from the lntop repo ([link](https://github.com/edouardparis/lntop/blob/650f1420d35b16f97f52dc828f8c9a095bc6a7c9/ui/keybindings.go)) to work out what keys are used for what purpose.
Added a section to the guide listing all the keys and what they do.
Test:
* Install lntop
* Go through the explanations and try out each key and see if result is as described
Maintenance: Occasional updates when/if the lntop developper add or changes the keys

Add section on how to use lntop

---

btcrpcexplorer.md

This change updates BTC RPC Explorer to the lastest version and fixes the update instructions.
The latest release brings a ton of new features and is well worth the update.
Also, the current update guide has some issues that need to be addressed. The NPM install process changes files in the repository that block the checkout of a newer branch later on. The repo needs to be reset first, and local changes discarded.
Additionally, v3.3.0 was tagged without a date, not sure how that's even possible. But this breaks the 'git describe' command,
so at least temporarily we fall back to 'git tag'.
see above
fixes https://github.com/raspibolt/raspibolt/issues/826

BTC RPC Explorer: update to v3.3.0

---

.github/workflows/stale.yml

Monitor the activity of GitHub issues and pull requests, mark them as stale after a period of inactivity, and automatically close them if no activity occurs after.
**The specific timing and wording when closing items are open for debate, feedback is welcome!**
Support is given on a best-effort basis. In my experience, issues quickly become irrelevant, and even if help is finally provided
with some delay, the original author usually no longer comes back. The same goes for pull requests that don't gain any traction. They become outdated, although on a longer time scale.
To keep open issues and pull requests relevant, it's good practice to close stale ones. This change proposes to mark issues as stale after 60 days of inactivity, and close them one week after, if no activity occurs. Pull …

github-actions: warn and auto-close issues & prs

---

bonus/bitcoin/electrum-personal-server.md.md
bonus/bitcoin/specter-desktop.md
bonus/index.md
bonus/lightning/additional-scripts.md
bonus/lightning/auto-unlock.md
bonus/lightning/remote-lncli.md
bonus/lightning/static-backup-dropbox.md
bonus/lightning/zap-ios.md
bonus/lightning/zap.md
bonus/lightning/zeus-over-tor.md
bonus/raspberry-pi/command-line.md
bonus/raspberry-pi/odroid-setup.md
bonus/raspberry-pi/system-overview.md
bonus/raspberry-pi/trezor-agent.md
bonus/raspberry-pi/upgrade-external-drive.md

This PR adds a yellow 'Status: Not tested v3' label to all the untested legacy bonus guides.
It also add a 'Labels' section to the 'Bonus Section' index page that introduces the reader to the meaning of these labels.
For now, two categories of labels exist: Difficulty (Easy/green, Intermediate/yellow, Hard/red) and v3-tested status (tested/green or not tested/yellow). More labels could be added later on if judged useful.
To warn readers that a bonus guide might not work on a RaspiBolt v3 and might require some slight or heavy adaptions to make it work.
Added the yellow status label to all untested legacy guides.
Added a Label section to the bonus section. 
Check that the label syntax is correct as they are not displayed in the Github preview.

Add 'Not tested v3' labels to untested legacy bonus guides + introducing labels in 'Bonus Section'  index page

---

bitcoin-core.md

This pull request changes the method to ensure that the .cookie file is group accessible.
Bitcoin Core is accessible to applications run by different users through the authentication cookie. Users that are a member of the group "bitcoin" need read-only access to /data/bitcoin/.cookie and can then authenticate themselves without username and password.
By default, Bitcoin Core does not create the .cookie file with group permissions. As of now, the bitcoind argument `sysperms=1`
is used with UMask=0027 to override this. Bitcoind only allows this if `disablewallet=1` is set. This breaks compatibility with
applications that rely on the Bitcoin Core wallet like JoinMarket or Electrum Personal Server.
This change uses a different method that allows to keep the wallet enabled: executing a shell …

bitcoind: use 'startupnotify' for group perms

---

bonus/raspberry-pi/system-overview.md

When updating the system overview, netcat was removed by mistake.
This commit adds it again.
Reported by https://twitter.com/AsyncLuck/status/1473714386162302978

system overview: re-add netcat

---

bitcoin-core.md

Update bitcoin.service status output to help avoid confusion.
Closes #853

Update bitcoind.service status output

---

rtl.md

A small fix for a broken link in the RTL guide.
Check that the new link is working and does not throw a 404 error.

Fix RTL broken link

---

electrs.md

The Electrs guide mentionned that Bitcoin Core was not meant to hold funds and that its wallet was deactivated. However, this is not the case anymore since #846 . This PR removes the part of the sentence that mentions the deactivated wallet.
For consistency
Removed a few words in `electrs.md`
Just check that the modified sentence is correct.

Removed outdated reference in Electrs guide about deactivated Bitcoin Core wallet 

---

bitcoin-core.md

Correction for a tiny typo in the Bitcoin Core guide ("commdands" instead of "commands")
Check that the typo is fixed

Fix small typo in Bitcoin Core guide

---

operating-system.md

Raspberry Pis are not always configured to boot from USB devices.
It has to be enabled by booting once from a microSD card containing this setting.
This is very confusing for new users and needs to be addressed.
This change
* explains this issue
* gives simple instructions
* links to a detailed external guide
Check if the instructions make sense. No ongoing maintenance is required.

os: enable "boot from usb" configuration

---

electrs.md

Simple fix for an error in the Electrs update instructions.
The current guide does not work:
There's no need to specify the repository here, the command works without it.
Update Electrs using these instructions

electrs: fix update instructions

---

bitcoin-core.md

Adding an expected warning as well as prepending a command to use sudo.
This PR fixes #864 and succeeds #865 based on [this comment](https://github.com/raspibolt/raspibolt/issues/864#issuecomment-1003272244) by @c-mannix 
This change will prevent future confusion by users inspecting the bitcoind service and tailing the debug.log file.
* Now including the warning in the output
* Explicitly directing use of `sudo` with tail command
* 
Fixes #864 
Test the command by running `tail -f /home/bitcoin/.bitcoin/debug.log` successfully.

Update bitcoin-core.md: include warning and sudo when tailing debug.log

---

system-configuration.md

This PR is a proposal to remove the installation of the `qrencode` package in the core guide.
Note: what about `jq`, do we use it in the core guide..? I can't find where.
The package is not used at any point in the core guide, so no reason to install it by default (security risk)
Deletedt the package name from the command
Just need to make sure that we indeed do not need this package anywhere in the core guide

Remove qrencode package installation from core guide as not used

---

rtl.md

Fix the path of RTL sample config file.
The sample file has once again moved location (it was recently put in the `/docs` directory which does not exist anymore and it's back in the root directory).
fixed path
Check that the corrected path is the right one

Fixed path to RTL sample config file

---

bonus/bitcoin/white-paper.md
bonus/lightning/additional-scripts.md
system-configuration.md

This is a proposal to update the list of packages we install in the "System configuration" of the guide: probably only `git` need to be installed.
Presently, the command installs the following packages: `wget` `curl` `gpg` `git` `htop` `jq` 
* Based on the [list of packages included in RaspiOS Lite 64-bit](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64-lite.info), `wget`, `curl`, `gpg` and `htop` are already shipped with the OS and therefore do probably not need to be installed (moreover, `htop` is never used in the core guide)... or do they..?
* `jq` is not part of the OS but is not used in the core guide, only in bonus guides (albeit several of them: system overview, white paper, lnchannels, lnbalance). …

Updated list of default packages to install

---

bitcoin-core.md
system-configuration.md

/data owned by admin, and bitcoin user creation belongs in the Bitcoin section
Postpone the bitcoin user creation until it is being used
Considering writing a testnet version of the bitcoin section... it would be pretty similar except for the user creation. So to keeps things consistent, might be a good idea to create the bitcoin user in the Bitcoin section.
Removed the bitcoin user creation in the `System Configuration` section, moved it to the `Bitcoin` section. A tad below, in the former section, the `/data` folder was created and owned by the bitcoin user. This was part of another discussion, wondering if that's the right thing to do. As that user simply doesn't exist at that point anymore, it makes much more sense to give that folder to the `admin` user.
I fear …

/data owned by admin, and bitcoin user creation belongs in the Bitcoin section

---

operating-system.md

Fixes a minor illogical statement in the Pi Imager section of the guide + adds a version requirement for the Imager
Specifically: 
* Adds that v1.7+ is required (no cogwheel in v1.6 and no advanced options at all in version below 1.6).
* This addition is to reduce the numbers of users raising issues such as "Can't find the cogwheel" etc 
* Instead of using "[...] we will use the Raspberry Pi imager v1.7+ [...]", we could use a sentence like "[...] we will use the latest version of the Raspberry Pi Imager [...]" which is maybe easier to read.. wdyt?
* Added implicit 'Start the Raspberry Pi Imager' to section where the OS is selected and used bullet points to make the commands clearer. And removed the 'Start the Raspberry Pi Imager' from the following section. as the Imager was already …

Small changes for Pi Imager guidelines

---

bitcoin-core.md
privacy.md

This change fixes https://github.com/raspibolt/raspibolt/issues/907
It's a bug. We don't like bugs. 
https://github.com/raspibolt/raspibolt/pull/904 moves the creation of user "bitcoin" to the "Bitcoin Core" section. The command to add user "bitcoin" to group "debian-tor" is moved to this section as well.
Fixes https://github.com/raspibolt/raspibolt/issues/907
Should be straight-forward

move tor-config for user bitcoin

---

static-channel-backup.md

Fixes dead link in SCB guide.
[Dead link identified here](https://github.com/raspibolt/raspibolt/issues/915#issuecomment-1042963750)
Replaced wrong URL with the right one
Double-check the link is working.

Fixed dead link in SCB guide (another one)

---

static-channel-backup.md

This PR fixes a bug related to the location of the local GitHub repository for the remote backup of the SCB. As it is, the repo is cloned in `/home/lnd` instead of `/data/lnd`
The remote backup guide does not work as is.
I propose a simple `cd /data/lnd` just before cloning the repo + some minor related changes due to this added step
An alternative would be to add a destination argument to the `git clone` command. However, I encountered some issues with this technique. So I wonder if moving first to the desired directory might not be more fool-proof..
Wdyat?
Fixes #928 
Try out the new commands and see if it works as intended.

Fixes bug with SCB repo cloning destination

---

lnd.md

This PR adds an option to `lnd.conf` to enable [keysend payments (send/receive)](https://docs.lightning.engineering/lightning-network-tools/lnd/send-messages-with-keysend).
The option is described here: https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L385-L388
To add a useful LND functionality by default.
* Added a single-line option in `lnd.conf`
No test needed, maybe just check that there is no typos..

Add keysend option in lnd.conf

---

bonus/lightning/lntop.md

* Updates the lntop bonus guide to latest released binary (from v0.2.0 to v0.3.0)
* Updates heading level to match rest of the guide
* Adds an "Update" and "Uninstall" sections
To keep the lntop guide up-to-date
Fixes #885 
Install lntop from scratch to check that the updated guidelines are ok.
Update and uninstall lntop to check the thw 2 new sections are ok

Update lntop to v0.3.0 + new Update & Uninstall sections

---

faq.md

See discussion in #933. The PR adds presently missing guidelines concerning the ownership of the Bitcoin and LND data folders when migrating from v2 to v3.
To improve the change of users successfully migrating their data to a new node
Fixes #933

Bitcoin & LND data migration: added -og flag to rsync command + LND chown command

---

bonus/lightning/remote-lncli.md

I added the permissions allowed/denied for the two mission control functions (`querymc` and `resetmc`) to the macaroons permissions table.

Add mission control permission to macaroons table

---

guide/bonus/lightning/charge-lnd.md

This change fixes two internal links in the "charge-lnd" bonus guide.
The bonus guide used full URLs including the raspibolt.org domain, which we should avoid. I did not catch these broken links when testing the restructured guide in my own fork, as the links pointed to the not-yet-restructured public guide. 
This change fixes these two links by using relative paths, pointing to the local markdown files.
Check the links of the "charge-lnd" bonus guide.

charge-lnd: fix internal links

---

guide/lightning/mobile-app.md

This PR proposed to:
* adds an APK install section for Zeus for Android users that cannot (e.g. can't find Zeus in Google Play) or do not want (e.g. for privacy goals) use Google Play
* fixes the font of a couple of commands to tap on the app (capitalized vs non capitalized) to match what the user sees on their phone
* switches the term "click" for "tap" in the section using the phone
* updated mobile-app.md
If desired, can download the APK and install it following the instructions in the guide to check that they are valid

Zeus guide: fixes mobile commands font + adds an APK intall section

---

guide/bonus/lightning/rebalance-lnd.md

Fixed issue where pip3 install fails to install to ~/.local/bin

Fix for installing to correct path

---

guide/bonus/lightning/circuit-breaker.md

Update to newest version. Affects "Circuit Breaker" bonus guide.

Bump Go version to 1.17.8

---

guide/bonus/lightning/balance-of-satoshis.md

Connect BoS to Telegram via proxy (Tor/VPN/other proxy) using built-in flag `--use-proxy <file>` instead of `torify`.
Proxy BoS to Telegram via Tor or VPN or custom proxy.
Use built-in flag `--use-proxy` which is available since BoS version 11.50.1.
Please review, implement and test. Unfortunately I'm not using a rpi setup, so this was translated. It should be set and forget once installed.

BoS: use built-in flag `--use-proxy` instead of torify

---

guide/bitcoin/electrum-server.md

Bump Electrs version to v0.9.6 and update command to fetch latest release tag for upgrade guide.
Resolves #951. Fixes #970.

Bump Electrs version and update command to fetch latest release tag

---

guide/bonus/bitcoin/electrum-personal-server.md

Instructions to create and autoload a dummy default wallet within bitcoind, missing which eps will not load.
To make eps start
Elite skills
- [x ] simple bug fix
Fixes # (link issue) https://t.me/raspibolt/9452
Just did this on my fresh install as I encountered this problem, no further testing and maintenance are expected

add instructions to create and autoload bitcoind wallet

---

guide/bonus/lightning/charge-lnd.md
guide/lightning/channel-backup.md

Based on the implemented backup option with Dropbox, I wanted to switch the backup to the new variants. At the same time I also wanted to make a pull request to fix issue #958. I found a few more small bugs and fixed them.
Fixes #958 
Fixes #981
So I got the following error messages because the file channel.backup exists with a size of 0 bytes and root access rights:
admin@raspibolt:~ $ ls -al ~/.lnd/data/chain/bitcoin/mainnet/channel.backup
-rw-r--r-- 1 root root 0 Feb  1 09:58 /home/admin/.lnd/data/chain/bitcoin/mainnet/channel.backup
......
Apr 10 17:29:04 raspibolt lnd[114726]: 2022-04-10 17:29:04.547 [ERR] LTND: Shutting down because error in main method: unable to start server: unable to refresh backup file: unable to extract on disk encrypted SCB: payload size too small, must be at …

LND Channel backup. Bug fixed. Motivated by Issue #958

---

guide/bonus/lightning/lnbits.md

Fixes missing / outdated deps for some OSes (tested on Ubuntu Server 20.04.4 LTS) in LNBits guide.
Fixes #985.

Fix missing / outdated deps for some OSes in LNBits guide

---

guide/bonus/lightning/index.md
guide/bonus/lightning/thunderhub.md

Revisiting stuck PR #735 and adding left open comments. 
ThunderHub is a good looking web gui for node management with one of the best UIs out there. Therefore Raspibolt guide shouldn't miss out on this. 
Following installation instructions provided by ThunderHub's github repo and combining them with RTL's setup guide (admin.macaroon workaround).

Add bonus guide: ThunderHub

---

guide/bonus/bitcoin/mempool.md

Several bug fixes for the Mempool bonus guide:
- Fixes #918 : states the requirement of running Mempool with a minimum of 4 GB of RAM
- Fixes #965 : add a Tor proxy in Mempool config to fetch prices privately
- Fixes #966 : fixed command typo: chown -> chmod 
- a couple of minor wording changes for improved clarity

Several small bug fixes for Mempool bonus guide

---

resources/20-raspibolt-welcome

Get current local installed / running BTC RPC Explorer and RTL version info from `npm` not `git`.
1) `git fetch` does not mean it's actually installed (`npm install`) and running;
2) `git describe tags` will not always return latest version.

System overview: Get running version of BTC RPC Explorer and RTL from `npm` not `git`

---

guide/bitcoin/desktop-wallet.md
guide/bonus/raspberry-pi/homer.md

* Sparrow: Fixes OSX shortcut to open settings
* as suggested by @craigraw https://github.com/raspibolt/raspibolt/pull/967#issuecomment-1113180274)
* Homer: Adds missing code block closing quotes to fix display issue
Check that the display issue with Homer is fixed and that the OSX command is OK.

Two small bug fixes for Homer and Sparrow

---

guide/bonus/lightning/lnbits.md

This PR simply replaces port 4002 by port 4003 for the LNBits guide
See Issue #997 : Port 4002 already used by ThunderHub which leads to errors if both programs are being run at the same time.
Fixes #997 
Check that all mentions of port 4002 in the guide have been replaced by 4003.

Changes LNBits nginx reverse proxy port to 4003 (4002 already used by ThundrHub)

---

guide/bonus/lightning/thunderhub.md

* Removed dark mode configuration lines in ThunderHub guide
Dark mode is the default value.
Source: https://docs.thunderhub.io/setup/#config
> THEME = 'dark' | 'light' | 'night' # Default: 'dark'
Fixes #1002

Removed dark mode configuration lines in ThunderHub as it is default

---

guide/bonus/lightning/lnbits.md

Bump LNBits version to 0.8.0.
[New version was released month ago](https://github.com/lnbits/lnbits-legend/releases/tag/0.8.0).

LNBits version bump (0.8.0)

---

guide/bonus/lightning/balance-of-satoshis.md
guide/bonus/lightning/charge-lnd.md
guide/lightning/web-app.md

Bump latest version fo RTL, charge-lnd and BoS and update commands to get latest release tags for upgrades.
Also updated sample `git verify-tag` outputs. Signature date/time will change witch each versions, checking fingerprint is more important.
See #987, same as was done there for Electrs.
P.S. Could we write some bot that automatically opens version bump PRs?

Bump versions and update instructions to get latest release tag from `git` (RTL, charge-lnd, BoS)

---

guide/bonus/bitcoin/index.md
guide/bonus/bitcoin/testnet.md

This draft PR adds a _Raspibolt on Testnet_ bonus guide page.
This PR is currently in draft mode because I'm still working on the Lightning part of the RaspiBolt guide, and so I expect more sections will be added before I'm through.
[See the in-progress page here](https://thunderbiscuit.github.io/raspibolt/bonus/bitcoin/testnet.html).
Testnet is awesome, and to quote the page: _Helping bitcoiners run a full testnet setup is a goal worthy of the RaspiBolt._

Add testnet bonus page

---

guide/lightning/lightning-client.md

Updates LND guide to v0.14.3
There are no breaking changes in this update: https://github.com/lightningnetwork/lnd/releases/tag/v0.14.3-beta
> This release contains only a series of bug fixes, and doesn't introduce any backwards compatible changes (database migrations, etc) from the prior version.
Check that all necessary changes have been made

Updates LND guide to v0.14.3

---

guide/lightning/lightning-client.md

Fixes https://t.me/raspibolt/10507
LND guide: Hyperlink named "Olaoluwa Osuntokun" goes to Guggero's keybase website. Redirected.

LND guide fix: hyperlink gone wrong

---

guide/bonus/bitcoin/mempool.md

Allow `mempool` mysql (mariadb) user access only from localhost. It is good common security practice. Does not change much in practice with default mariadb config, as only localhost access is allowed to server, but can change, if for some reason remote (for example, LAN) access is enabled later.
Also using hardcoded "mempool" as a password is not great, but probably not so important right now, as mempool is the only service in RaspiBolt guides that users mysql. But better would be to generate random password. I can add a commit on top of this that changes that too, but will complicate guide little bit.

Grant mempool mysql access only to localhost and use random password

---

guide/bonus/lightning/balance-of-satoshis.md

Pointing out a new option to `bos telegram` command `--use-small-units` as sidenote. 
This makes amounts (satoshis) in Telegram messages display like common numbers: `0.00011111` -> `11,111`/`11.111` (depending on one's locale).
Because @Swissnode kept asking for it. 
Show how to add parameter to bos' systemd.service.
Fixes #1003

BoS guide: add parameter --use-small-units

---

guide/lightning/lightning-client.md

Update LND guide to v0.15.0.
Most important new feature in this version:
> There is one database migration for this version in lnd: two new accounting related fields are added to the open channel information. This migration enables a 95% reduction in the disk space consumed by new channel updates.
See [LND v0.15.0 release page](https://github.com/lightningnetwork/lnd/releases/tag/v0.15.0-beta).
Since this version LND also timestamps the manifest file along with its signature with [OpenTimestamps](https://opentimestamps.org/). This does not include this check, will open separate issue about that.

LND version bump (v0.15.0)

---

guide/lightning/lightning-client.md

Existing LN+ watchtower is outdated, see their announcement on their website (https://lightningnetwork.plus/watchtower):
The PR replaces the old address with the new recommended one (displayed furtther down the webpage: https://lightningnetwork.plus/watchtower
The issue was flagged here: https://t.me/raspibolt/11758
Test the new watchtower

Replaces outdated LN+ watchtower address with the new one

---

guide/bitcoin/electrum-server.md

The Electrs configuration file option `index_lookup_limit` is now disabled by default because not useful for operators using Electrs for themselves only. 
See #888 for more detailed explanations and useful links.
Fixes #888 
Run Electrs with the deleted conf option

Remove outdated "index_lookup_limit" from config

---

guide/bonus/raspberry-pi/boot-from-microsd-card.md

Added `chown admin:admin /data` which is included in the default configuration guide, but was missing in the _Boot from microSD_ bonus guide resulting in permission denied when trying to create the bitcoin directory.
`mkdir: cannot create directory '/data/bitcoin': Permission denied`
Fixes https://github.com/raspibolt/raspibolt/issues/1038

Fixed permission issue in microSD bonus guide

---

guide/raspberry-pi/privacy.md

Added a seperate section for macOS Users on how to setup remote SSH through Tor.
Using `torify` or `torsocks` as suggested will cause issues with _System Integrity Protection_.
```text
ERROR: /usr/local/bin/ssh is located in a directory protected by Apple's System Integrity Protection.
```
Simply turning SIP off is dangerous and not recommended, even though it's probably the fastest solution to this.
The solution below simply adds a SSH config file with a proxy command. Once set up, one can conveniently SSH to the Pi with `ssh HOSTNICKNAME`.
Tested on macOS 12.4.
I am unsure from what version of macOS onwards this issue occurs, but some users on StackExchange have suggested 10.11 i.e. "El Capitan" which should affect almost every macOS user.

Section for macOS users on remote SSH through Tor

---

guide/lightning/lightning-client.md

Without this command, an incorrect stop occurs - systemd sends a kill signal, which is not processed correctly by LND - part of the services inside LND stops, but the process itself continues to work. Then systemd sends signal `9`, which kills the process.
```
Jul 21 09:45:35 electrs lnd[20686]: 2022-07-21 09:45:35.719 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
Jul 21 09:46:35 electrs lnd[20686]: 2022-07-21 09:46:35.719 [INF] WTCL: (anchor) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
Jul 21 09:46:35 electrs lnd[20686]: 2022-07-21 09:46:35.719 [INF] WTCL: (legacy) Client stats: tasks(received=0 accepted=0 ineligible=0) sessions(acquired=0 exhausted=0)
Jul 21 09:47:17 electrs …
```

Adding the lnd stop command in systemd unit file

---

guide/lightning/web-app.md
resources/20-raspibolt-welcome

RTL has tags also for RC (release candidate) pre-releases, you want to ignore them when checking for latest version.
Currently, without this change, will think v0.12.4-rc1 is the latest, after - v0.12.3.
Ignore git tags that contain "rc".
Just check before / after bash oneliner result.

Ignore RC pre-releases for RTL

---

guide/raspberry-pi/privacy.md

- Added monitoring tor logs
- Standardized comment for ssh hidden service torrc config
Improve tor monitoring to detect possible errors in the network
adding `sudo journalctl -f -u tor@default` command
adding `# Hidden Service SSH server` comment in torrc file
The changes were tested by myself.

[FEATURE REQ] Add tor feature + comment ssh hidden service in privacy section

---

guide/lightning/lightning-client.md

The setting sync-freelist=true caused heavy bloating of the channel.db (several GB per day). Disabling this setting fixes this issue.
Related:
https://github.com/lightningnetwork/lnd/issues/6800
https://github.com/lightningnetwork/lnd/issues/6744
https://github.com/lightningnetwork/lnd/issues/6737
https://github.com/lightningnetwork/lnd/issues/6837#issuecomment-1218342468

Change sync-freelist to false in the lnd.conf

---

guide/bonus/raspberry-pi/homer.md

The logos were in VajraOfIndra/awesome-bitcoin-logos repo. They now are in raspibolt/awesome-bitcoin-logos. The guide is updated to reflect this change.
Test the updated links that they redirect to the new repo

Changes bitcoin logo repository path in Homer guide (repo is now part of RaspiBolt orgranization)

---

guide/bonus/raspberry-pi/ups-nut.md

- Fixes the wrong guide path
- Formatting of the code blocks for standardization with rest of the guide
Check path is correct & new code formatting is ok

Fix UPS-Nut guide path & code formatting

---

guide/bonus/raspberry-pi/index.md

The UPS NUT bonus guide did not have an entry in the Raspibolt bonus guides index. This PR adds such entry and link.
Added a new subsection "Resilience". 
But maybe could be placed under hardware? 
Note: It'd be useful to add a guide on how to choose and install a UPS.
Check the entry is there and the link is working

Adds UPS NUT bonus guide entry in index

---

guide/bitcoin/electrum-server.md

Bumped electrs version numbers to v0.9.9

Electrs version bump (v0.9.9)

---

guide/bonus/bitcoin/fulcrum.md

Improvement of `fulcrum.conf` configuration file and minor fix of redirect link wrong 
- Fixed wrong redirect link to Desktop Wallet core section
- Fixed `announce = false` parameter redundancy in `fulcrum.conf`
- Other minor redaction fixes
Following developer example-config:
https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf#L427-L435
```sh
#
#
#announce = true
```
DEFAULT: true if hostname and *peering are set*, false otherwise
https://raspibolt.org/guide/bonus/bitcoin/fulcrum.html#configuration
```sh
peering = false
```

[UPDATE BONUS GUIDE] Minor update of the Fulcrum bonus guide

---

guide/lightning/channel-backup.md

Push LND local channel remote backups to GitHub via Tor, not clearnet.
RaspiBolt configures LND to work as .onion service only by default. But without this change remote static channel pushes to github.com happen using clearnet. This way your real IP address ir revealed to github.com (Microsoft), together with your channel information.
Change git configuration for lnd user to use `torsocks ssh` instead of `ssh` to connect to GitHub.
Fixes #1065
Modify git config, do `touch /data/lnd/data/chain/bitcoin/mainnet/channel.backup` and check that new backup file is pushed to GitHub repository.

Push remote LND static channel backups to GitHub via Tor

---

guide/lightning/lightning-client.md

Section "lightning->lightning-client ->Make a Lightning payment"
it's write to pay in  tippin.me.
But in these way you get a LNURL that not works in LND.
In the guide section, to try first LN invoice payment,  the link to  tippin me  gives an  LNURL .
LNURL not works in LND right now.
Write a better explanation and a cli command to pay the Stadicus node

Make a Lightning payment. Fix LNURL pay section with lncli command 

---

guide/lightning/lightning-client.md

Two typos flagged by @dunwright in #1092:
Fixes #1092

Fixes two typos in LND "Open a channel" section

---

guide/bonus/bitcoin/index.md

- Adds a missing separator in the bonus Bitcoin index page
- Rewording of the Safu Ninja blurb in the index to make it easier to read/understand

Add missing separator + rewording of Safu Ninja blurb

---

guide/bonus/lightning/clboss.md
guide/bonus/lightning/cln.md

Renaming everything related to core lightning from "cln" to "lightningd" as described in official core lightning docs to stay compliant to docs, surrounding tools, plugins and other things we don't know about.
see What
Renaming "cln" to "lightningd"
- user
- user dirs
- data dirs
- conf files
- systemd service
- plugins
- etc.

CLN: renaming cln to lightningd

---

guide/bonus/lightning/cln.md

Reverts instructions to build from source. 
According to CLN docs: poetry is used for development environments, pip3 and make for production environments. 
Fixes #1057
poetry didn't work on arm64 systems causing error on `poetry install`. On amd64 systems it did work tho.
Replacing poetry installation steps with pip, configure and make commands. 
Fixes #1057

CLN: fix building and installation instructions

---

guide/bonus/bitcoin/specter-desktop.md

Specter Desktop bonus guide wasn't updated since RaspiBolt v2 and wasn't working as is on v3. This is minimum changes I made to get it working on v3 + version bump (required for newer Python version support, among other things). Most breaking was migrating from Bitcoin RPC user/password to cookie auth in v3. Unfortunatelly, Specter does not allow to specify RPC cookie file location, only way is to link whole bitcoin datadir and then let it autoguess settings.
Not sure this is perfect, don't have too much experience with Specter so far, but at least it works again.
Fixes #1041

Fixes for Specter desktop guide (mainly for RaspiBolt v3 + Specter version bump)

---

guide/bonus/lightning/cln.md

Poetry was removed from CLN install guide in #1094, but there was still left reference to it in sentence describing commands. Remove that.

CLN: Remove reference to `poetry`

---

guide/raspberry-pi/preparations.md

This PR is a proposal to add a recommendation to harden the security of the user home network and devices before starting building their node  (e.g. set WPA2, disable WPS, change admin password etc).
This is done through a new section at the end of the "Preparations" chapter; after creating all the passwords. The section introduces the rationales for securing the home networks and devices and points to a 3rd party tutorial (external URL).
While I prefer avoiding 3rd-party tutorials if possible, making an internal guide that goes through all the security tips might make that chapter a bit too long and be considered OOT.. (?)
I selected this guide: https://restoreprivacy.com/secure-home-network/ but if you know of a better/more reliable or trustworthy tutorial, please suggest an alternative …

Add a "Secure your home network and devices" section to the "Preparations" chapter

---

guide/bonus/lightning/balance-of-satoshis.md

There is a typo in the rebalancing commands, the `--out` flag should be node B, not node A, as pointed out in #1099.
This PR contains:
- a fix for the typo: `NODE_A_PUBKEY `-> `NODE_B_PUBKEY`
- a rewording of the command introductory sentence to make it clearer  
Fixes #1099 
- Check that the typo has been fixed everywhere it appears.
- Check that the rewording of the instructions are clearer

Fixes typo in rebalancing command + small rewording of explanations

---

guide/raspberry-pi/privacy.md

This can lead to significant improvements in the correct running of the Raspibolt nodes.
The Tor Project maintains its own Debian package repository. Since Debian provides the LTS version of Tor, this might not always give you the latest stable Tor version. Therefore, it's recommended to install tor from Tor official repository.
In addition, obtaining the latest release could help mitigate the current constant attack that the Tor network has been facing for months.
- Added the process to enable Tor Package Repository and install it from the official Tor repository
- Other improvements to Tor installation process
I tested all and is working fine for me:
```sh
$ tor --version
> Tor version 0.4.7.10.
[...]
```
```sh
tor          830      debian-tor    6u  IPv4  22995      0t0  TCP …
```

[UPDATE] Update privacy section to enable official Tor Package Repository

---

guide/raspberry-pi/security.md

Uppercase `SSH` gives me an error, lowercase works (Ubuntu Server).
```
admin ~ ₿ sudo ufw allow SSH 
ERROR: Could not find a profile matching 'SSH'
admin ~ ₿ sudo ufw allow ssh
Skipping adding existing rule
Skipping adding existing rule (v6)
```

`ufw allow ssh` should be in lowercase

---

guide/bonus/lightning/lnbits.md

This PR adds an Uninstall section to the LNBits bonus guide.
To remove LNBits and keep the node tidy and without unused files.
Fixes #1114 
Uninstall LNBits from the node.

Adds an Uninstall section to the LNBits bonus guide

---

guide/bonus/lightning/lightning-terminal.md

A PR to update Lighting Terminal to v0.8.1
- The guide is outdated (many versions behind)
- v0.8.1 contains the hot fix of LND v0.15.2. It does not really matter for this guide as the guidelines assume we are using an external LND node and NOT the one contained in Lightning Terminal... but just in case it's safer to have the guide with the version that contains the bug fix just in case a user would wnat to try out to use the LND as part of LiT..
- Verify syntax
- If possible, update on a node with LiT

Update Lightning Terminal to v0.8.1 (contains the LND v0.15.2 hotfix)

---

guide/bonus/lightning/cln.md

Small bugfix to prevent port collision (RTL / cl-rest.js on port 4001) when generating access.macaroon by manually starting `cl-rest.js`.
better user experience
PR of a PR =)

[BUGFIX] prevent port collision on macaroon creation

---

guide/lightning/lightning-client.md

Hotfix upgrade for chain sync.
gpg Signature timestamp needs to be adjusted once 0.15.4 is released

Upgrade to lnd 0.15.4

---

guide/bitcoin/blockchain-explorer.md

_(following up the clossure of PR #1118 - this PR has a more focused scope)_
tl;dr: A PR to fix #848 : Restarting Bitcoin Core does not break BTC RPC Explorer
Bug: When Bitcoin Core is restarted, a new cookie file is generatd. But the Explorer does not notice and still use the older cookie file, which prevents the user to acces the Explorer (due to wrong Bitcoin Core RPC authentification). This is a mishandling of the cookie file by the Explorer and should be fixed in the Explorer codebase ittself. 
However, for the time being, we can use a work around.
This PR configures the systemd service files bitcoind.service and btcrcpexplorer.service in a way that when Bitcoin Core restarts (or stops and starts again), the BTC RPC also restarts (or stop and starts again). In this way, the Explorer …

Fixes #848: Restarting Bitcoin Core without breaking BTC RPC Explorer

---

guide/bitcoin/electrum-server.md

Bumped electrs version numbers to v0.9.10, Issue https://github.com/raspibolt/raspibolt/issues/1147
I ran into a little error trying to checkout the new branch:
```
error: Your local changes to the following files would be overwritten by checkout:
internal/config_specification.toml
Please commit your changes or stash them before you switch branches.
```
Maybe this is just me, but I cannot recall making any changes to that file so I added a little comment how to ignore something like this (simply by forcing with `-f`).

Electrs version bump (v0.9.10)

---

guide/bitcoin/electrum-server.md

[Man page](https://linux.die.net/man/1/install) for `install`:
> This install program copies files (often just compiled) into destination locations you choose.
Some comparisons between cp and install are discussed [here](https://unix.stackexchange.com/questions/104982/why-use-install-rather-than-cp-and-mkdir). Notably:
> If copying over an existing file, cp overwrites the existing inode of the file, while install always creates a new inode for the same file name
Previous discussions on this change in closed PR #1102  [here](https://github.com/raspibolt/raspibolt/pull/1102#discussion_r981821131).
More explicit and cleaner way to install & update Electrs
Update Electrs using new command

Use "install" instead of "cp" when installing or updating Electrs

---

guide/bitcoin/electrum-server.md

A few improvements for the Update section of the Electrs guide as already discussed in closed PR #1102:
1. add `git clean -xfd` : suggested [here](https://github.com/raspibolt/raspibolt/issues/747#issue-956434374)
2. add `git verify-tag v0.9.10`: suggested [here](https://github.com/raspibolt/raspibolt/issues/747#issuecomment-1056786273)
3. fix typo in comment: "Restart" instead of "Start"
Addresses some suggestions from @Kixunil in #747 
More robust and safer update process
Update Electrs using the new commands.

Enhancements for the "Update" section of Electrs

---

guide/raspberry-pi/privacy.md

Two small fixes in Tor / Privacy guide: 
- wrong port: 9150 (Tor browser) -> 9051 (control port)
- 9051 only shows after activating controlport, so verifying open ports at a later point of time makes more sense to me.
You gotta do the right thing!
Replace and copy / pasta.

[UPDATE GUIDE] Tor: fix port and order

---

guide/raspberry-pi/security.md

I found `ChallengeResponseAuthentication` as a deprecated parameter in the docs
Changed deprecated parameter `ChallengeResponseAuthentication` to `KbdInteractiveAuthentication`
"ChallengeResponseAuthentication is a deprecated alias for this."
ref: https://man7.org/linux/man-pages/man5/sshd_config.5.html
I tested all and is working fine for me

[UPDATE SECURITY GUIDE] Minor fix of a SSH config deprecated parameter

---

guide/bonus/lightning/lndg.md

Based on https://t.me/c/1442363505/33503 `htlc-stream-lndg.service` is set to `Restart=always` instead of `on-failure`.
Avoiding stuck service due to restarting method not activating.
Change is done in v1.4.0 branch of LNDg: https://github.com/cryptosharks131/lndg/blob/v1.4.0/systemd.md#htlc-failure-stream-data
Simple service file modification.

[UPDATE BONUS GUIDE] LNDg - htlc-stream-lndg - `Restart=always`

---

guide/raspberry-pi/security.md

PR to fix following issue: [https://github.com/raspibolt/raspibolt/pull/1164#issuecomment-1317018116](https://github.com/raspibolt/raspibolt/pull/1164#issuecomment-1317018116)
> Should the instructions for the changed lines be clarified since the default configuration file still includes the option's deprecated alias? Currently, the new KbdInteractiveAuthentication option must be manually added and the old option removed or commented out. The current instructional text only refers to "uncommenting the following two options" and the second option is currently not there to be uncommented.
Split the instruction in two parts. for the s/key option, ask to add a new line with the new superceding option (not present in the config file of the OS) below the commented out outdated option
> * Below …

Fix problematic SSH config option instruction

---

guide/raspberry-pi/security.md

Fix small typo in SSH guide: duplicated "the"

Fix small typoin SSH guide

---

guide/bonus/lightning/regolancer.md

Changed the upgrade command from a specific version to the latest one. This makes it easier for users to upgrade, since they don't need to check the exact version number of the latest release.

Improve the Upgrade section of the regolancer bonus guide

---

guide/bonus/lightning/cln.md

Adding additional information on how to expose CLN REST over Tor and generate a QR code for Zeus node configuration.
These change exist in the documentation for LND, but it is left largely to the user to figure out how to fill the gaps if they choose to run a CLN node.
Copied proces from LND documentation and help on QR code generation here:
https://github.com/ZeusLN/zeus/issues/515
along with linked Twitter post and some help from `elkaladiente` in Rapibolt Telegram channel.
- [x ] independent bonus guide
Test by trying to connect Zeus application to CLN with QR code over Tor.

Instructions to add CLN REST over Tor and CLN QR code generation for Zeus

---

guide/bitcoin/bitcoin-client.md

Update bitcoin-client.md to Bitcoin version 24.0
Add streamlined upgrade section to bottom of guide
Include .ots verification in upgrade section
Makes upgrading easier
Adds .ots verification for upgrades
as above
Fixes # 1190
https://github.com/raspibolt/raspibolt/issues/1190

Bitcoin guide update to 24.0.1 with OTS verification & OTS installation fix

---

guide/raspberry-pi/security.md

After installing ufw I recieved the following error:
```
ERROR: Couldn't determine iptables version
```
new users may be confused
I added a note
- [ x] simple bug fix

docs: add note about ufw cannot determine iptables version issue

---

guide/lightning/lightning-client.md

In lightning-client section the links to api.lightning.community not works anymore
Fix the broken URLs in raspibolt guide
Update to the new URLs in api.lightning.community/api
- [ X] simple bug fix
Just click the links and see if works fine

Update links api.lightning with new path

---

guide/bonus/bitcoin/bitboxapp.md

Image link in updated BitBox guide is broken
Tested it offline now and it should work...

Fix broken image link in updated BitBox guide

---

guide/bitcoin/electrum-server.md

Update of electrs to 0.9.11
Release notes: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md#0911-jan-5-2023

[update guide] electrs v0.9.11

---

guide/lightning/lightning-client.md

This PR updates the core guide `lightning-client` (LND) to newly released version `lnd-v0.16.0-beta`. 
Also:  This PR removes some lnd.conf settings which are set to default values and therefore unnecessary to add to lnd.conf. For the sake of consistency, some values are changed from `=1` to `=true`.
Keeping up with latest developments and improvements (see release-notes).
Tested locally on amd64.

[GUIDE UPDATE] lightning-client - lnd-v0.16.0-beta

---

guide/bonus/raspberry-pi/system-overview.md

- References raspibolt-pulse repo in place of system-overview sample.
- assumes eth0 over wlan0, inverts guidance
- changed guidance to review script content before installing
Migrate from older system-overview to raspibolt-pulse
References the scripts in new raspibolt-pulse repo which are intended to work across versions of Raspibolt (1.x - 3.x), and provide info about alternative electrum server, lighting implementation, and lightning web app
References new repo and updated commands to install
Depends on https://github.com/raspibolt/raspibolt-pulse/pull/17

[UPDATE BONUS GUIDE] Update system-overview.md to reference raspibolt-pulse

---

guide/bonus/bitcoin/Jam.md

1. Update Bonus guide: JoinMarket webui (Jam) to v0.1.5.
2.  Fix Tor port (change from 80 to 443).
1. New [Jam release version v0.1.5](https://github.com/joinmarket-webui/jam/releases).
2. Jam is listening on SSL port (4020), hence Tor should listen on and forward port 443 rather than 80.
[Bonus guide: JoinMarket webui (Jam)](https://raspibolt.org/guide/bonus/bitcoin/Jam.html#bonus-guide-joinmarket-webui-jam) has been updated.
Tested with Jam v0.1.5.

[UPDATE BONUS GUIDE] JoinMarket webui (Jam) v0.1.5

---

guide/lightning/lightning-client.md

Typo in field of expected lncli response of listchannels.
The correct field is shown in the LND API Reference here:
https://api.lightning.community/api/lnd/lightning/list-channels#lnrpcchannel
Grepping for the incorrect field in the lncli response comes back empty.
Correction to the expected field.
Start with a lightning node with some active channels.
run: `lncli listchannels | grep channel_point`
channel_point field info is returned.

fix typo within lncli field in guide to close a lightning channel

---

guide/bonus/lightning/lightning-terminal.md

Updates the bonus guide "Lightning Terminal" to v0.10.0 
v0.10.0 requires LND version 0.16.2 (!)
New version, new features (autofees).
Following release docs: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.0-alpha

[UPDATE BONUS GUIDE] Lightning Terminal v0.10.0

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.16.3.
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.16.3.md)).

Update LND guide to v0.16.3

---

guide/bitcoin/blockchain-explorer.md

Update BTC RPC Explorer guide to the latest version: https://github.com/janoside/btc-rpc-explorer/releases/tag/v3.4.0
Have our node up to date
tACK!

[UPDATE] BTC RPC Explorer to v3.40 + add variable $VERSION

---

guide/lightning/web-app.md

Print version you are upgrading to when upgrading.
It is useful feedback. Currently you don't know to which version you are actually upgrading. You are just blindly assuming that `git tag...` oneliner does the magic.

RTL: Print version you are upgrading to when upgrading

---

guide/bonus/bitcoin/fulcrum.md

Guideline for Fulcrum storage requirements is out of date.
current `du`
```
30M	/fulcrum_data/blkinfo
17G	/fulcrum_data/txhash2txnum
10G	/fulcrum_data/utxoset
5.6G	/fulcrum_data/scripthash_unspent
165M	/fulcrum_data/undo
4.6M	/fulcrum_data/meta
69G	/fulcrum_data/scripthash_history
128G	/fulcrum_data
```
(actually a tiny bit smaller than the last time I ran it, but close enough)
Also see: https://github.com/cculianu/Fulcrum/pull/194
Fulcrum indexing takes forever AND is quite fragile; if you don't allocate the proper size disk / partition, the process could crash and corrupt the DB, forcing you to start from the beginning (ask me how I know!! Twice!!).
The power of a text editor.
Periodically revise the storage requirements... annually? Guesstimate that it's growing at …

[docs update] Update Fulcrum index size info

---

guide/bonus/lightning/cln.md

CLN REST certs upgrade note
When upgrading CLN REST plugin, user will need to copy over their prior `certs` directory in order to preserve the access credentials. Otherwise client apps like Zeus will lose connectivity.
Should be a helpful reminder to acknowledge CLN version and CLN REST versions are functionally related, probably upgraded together, and a manual port of credentials / certs is necessary because of the tarball install method in CLN REST documentation.
Upgraded and lost access, fixed and updated docs.
Peform an upgrade and make sure RTL and Zeus still connect.
Add some snazz if you …

CLN REST certs upgrade note

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.17.0
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.17.0.md)).
- Added flag to enable support to simple taproot channels (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L1476-L1477) | Attention: for the moment, this feature will be enabled only to private channels until the gossip 1.5 update is done, using `lncli openchannel --channel_type=taproot` 
https://lightning.engineering/posts/2023-10-03-lnd-0.17-launch/
https://github.com/lightningnetwork/lnd/releases/tag/v0.17.0-beta

Bump LND to v0.17 + added flag to enable simple taproot channels

---

guide/raspberry-pi/security.md

Add the command to install the nginx stream module incase of ``unknown directive "stream"`. 
I was making my way step-by-step through the guide but ran into the `unknown directive "stream" in /etc/nginx/nginx.conf:10` error when trying to validate the nginx config. It's not immediately clear what the
issue is for peeps unfamiliar with nginx modules. 
simple helper incase of nginx config issues.

guide/rpi: command for installing nginx stream module

---

guide/lightning/web-app.md

The old installation method  is deprecated 
```sh
$ curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
```
I changed the installation method using [distributions](https://github.com/nodesource/distributions/tree/master)
Running the setup_tls script I got a "Script Deprecation Warning" and a link to distributions repo
Trying following the guide
Change can be tested by running the deprecated script and following the installation guide. 
By following the updated guide, I was able to correctly install node v20.8.1 on my …

changed node.js installation method using nodesource

---

guide/bonus/lightning/cln.md

This PR updates bonus guide CLN (+ c-lightning-rest) to their latest versions: cln 23.08.1 and cln-rest v0.10.7.
Keeping CLN updated and playing with many new (experimental) features: anchors, dual-fund
Tested locally on amd64

[UPDATE BONUS GUIDE] CLN 23.08.1, c-lightning-rest 0.10.7, RTL 0.14.1config

---

resources/UTXOracle.py

Update UTXOracle to newest version. Today incorrect BTC/USD rate was calculated, caused by Ordinals transactions. This is a fix.
https://stacker.news/items/309946
Original file - https://utxo.live/oracle/UTXOracle.py.

Update UTXOracle to version 7

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.17.1
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.17.1.md)).

[UPDATE] Bump LND to v0.17.1

---

guide/bonus/bitcoin/fulcrum.md

Update Fulcrum guide to newly released v1.9.7 and a small fix of a missing variable environment addition on a command
Keeping up with the latest developments and improvements (see [release notes](https://github.com/cculianu/Fulcrum/releases/tag/v1.9.7)).
- Fixed a command

[UPDATE] Bump version Fulcrum and small fix

---

guide/lightning/web-app.md

Updating RTL to v0.15.0 supports `clnrest` interface for CLN (#1392)
Following instructions on https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.0

[UPDATE GUIDE] Update RTL v0.15.0

---

guide/lightning/lightning-client.md

Updates LND guide to newly released 0.17.4.
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/v0.17.4-beta/docs/release-notes/release-notes-0.17.4.md))

Bump LND from 0.17.3 to 0.17.4

---

guide/bitcoin/bitcoin-client.md

Update the Bitcoin Core guide to the latest release 26.1.
Keeping up with latest developments and improvements (see [release notes](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-26.1.md)).

Bump Bitcoin Core from 26.0 to 26.1

---

guide/bonus/lightning/cln.md

CLN configs `autocleaninvoice-cycle` and `autocleaninvoice-expired-by` were deprecated with v22.11 and EOL v24.02. https://github.com/ElementsProject/lightning/pull/7094
I had random startup failures on different Ubuntu Server machine running v24.02.2 (not a RaspiBolt, it's x86_64, but that shouldn't change things much here.

CLN: Remove deprecated configs

---

guide/troubleshooting.md

The troubleshooting page is out-of-date. It shows lnd under the user bitcoin, when it is run as the user lnd.
It could be confusing if the output doesn't match.
I just changed "bitcoin" to "lnd" where necessary and added commands to switch to lnd user when doing lnd stuff.

Update troubleshooting.md showing Lightning now running under the user lnd

---

guide/bitcoin/electrum-server.md
guide/bonus/bitcoin/dojo.md
guide/bonus/bitcoin/fulcrum.md
guide/bonus/bitcoin/specter-desktop.md
guide/bonus/bitcoin/testnet.md
guide/bonus/lightning/lightning-terminal.md
guide/bonus/lightning/remote-lncli.md

Change usage of "/home/bitcoin/.bitcoin" to "/data/bitcoin" for users other than _bitcoin_.
Change usage of "/home/lnd/.lnd" to "/data/lnd" for users other than _lnd_.
Change usage of "/home/lit/.loop" to "/data/loop" for users other than _lit_.
Links to `/data/bitcoin` and `/data/lnd` owned by a user should only be used by that user. Also, note that while home directories are `rwxr-xr-x` by default on Raspian, they are `rwx------` on Debian, making these changes necessary for Debian.
Replaced `/home/bitcoin/.bitcoin` with `/data/bitcoin` and `/home/lnd/.lnd` with `/data/lnd` where referenced by users other than _bitcoin_ and _lnd_.
Fixes #1443
No maintenance is necessary while bitcoind and lnd remain installed in `/data`.

Change usage of .bitcoin, .lnd, and .loop links

---

guide/lightning/lightning-client.md

Updates LND guide to 0.18.4.
Keeping up with latest developments and improvements.
Release notes:
* [0.18.0](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.0.md)
* [0.18.1](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.1.md)
* [0.18.2](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.2.md)
* [0.18.3](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.3.md)
* [0.18.4](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.4.md)

Bump LND from 0.17.5 to 0.18.4

---

guide/lightning/web-app.md

Update the RTL guide to reference the latest version of RTL (v0.15.4)
Update to latest version and minimize confusion for beginners as the guide references 0.15.0 but they will see v0.15.4 on their pi when running the command ``git tag | grep -E "v[0-9]+.[0-9]+.[0-9]+$" | sort --version-sort | tail -n 1``
Release Notes:
- [0.15.1](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.1)
- [0.15.2](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.2)
- [0.15.3](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.3)
- [0.15.4](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.4)

Bump RTL from 0.15.0 to 0.15.4

---

guide/lightning/lightning-client.md

Updates LND guide to 0.18.5.
Keeping up with latest developments, improvements and bugfixes.
Release notes - https://github.com/lightningnetwork/lnd/blob/0-18-5-branch/docs/release-notes/release-notes-0.18.5.md
This seems especially important ASAP, there seems to be some bug with 0.18.4 that allows to steal funds. https://x.com/PavolRusnak/status/1891967156104954164

Bump LND from 0.18.4 to 0.18.5

---

guide/bonus/bitcoin/joinmarket.md

Updates some outdated elements of joinmarket.md preparations section to align with joinmarket-clientserver merged PRs:
- Document Core wallet creation for v26 [#1617](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1617) 
- Use python3's venv module instead of virtualenv [#1396](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1396)
Ensures that users do not encounter errors when following the guide to install joinmarket on raspibolt.
Tested changes on my Raspibolt running Core v28 with no issues and successful install of Joinmarket.

Updated joinmarket.md to align with joinmarket-clientserver merged PRs

---

guide/bonus/bitcoin/Jam.md

Jam guide states to use dergigi for pgp signature verification which does not work for verifying Jam version 3.0 onwards.
On Jamdocs.org, for Jam version 3.0 onwards it states to use:
```
curl https://raw.githubusercontent.com/joinmarket-webui/jam-docker/refs/heads/master/standalone/pubkeys/tbk.asc | gpg --import"
```
https://github.com/raspibolt/raspibolt/issues/1479
Tested v.0.3.0 on my Raspibolt node (Pi4, Pi OS 64 bit, Debian GNU/Linux 12 (bookworm), Bitcoind v29.0) and no issues.

pgp sig update

---

guide/raspberry-pi/security.md

Update path to `/boot/firmware/config.txt`.
It seems to have changed from `/boot/config.txt` to the new one. In my Raspberry Pi I get:
```
$ sudo nano /boot/config.txt
DO NOT EDIT THIS FILE
The file you are looking for has moved to /boot/firmware/config.txt
```
I have
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
in my Raspberry Pi 4.

Update path to firmware configuration file
