raspibolt/raspibolt

raspibolt/raspibolt_50_mainnet.md

Hi,  
trying to figure out how to use Github, apologies if I'm doing something wrong with this pull request (please let me know what, though :) ). 
Just wanted to add some useful commands to the guide, because the official LND API documentation is quite difficult to tackle as a beginner. Hope that's useful.

Adding some useful 'lncli' commands

---

raspibolt/raspibolt_40_lnd.md
raspibolt/raspibolt_50_mainnet.md
raspibolt/raspibolt_updates.md

* Mainnet: more stable switch to mainnet, more conservative wallet creation
* Mainnet: useful examples for lncli (thanks @raindogdance)
* Mainnet: copy updated bitcoin.conf to user "admin" for credentials

Changes 2018-03-22

---

raspibolt/resources/20-raspibolt-welcome

Add: CPU temp, and Wallet & Channel balances

BONUS: Enhance raspibolt (MOTD) further

---

raspibolt/raspibolt_faq.md

Hi, first time i do a pull request :) 
I put the "how to upgrade LND" in FAQ section, but don't know if it is the right.
I copy the procedure from https://github.com/Stadicus/guides/issues/76 and follow Stadicus suggets, test it and that's all.

added "How to upgrade LND bin" section

---

raspibolt/resources/20-raspibolt-welcome

Fixing incorrect bitcoin cli command

Fixing incorrect bitcoin cli command

---

raspibolt/raspibolt_updates.md
raspibolt/resources/20-raspibolt-welcome

New method to check public availability of Bitcoin Core, using netcat

Check public availability of Bitcoin Core

---

raspibolt/raspibolt_64_electrum.md

Solution to issue #133 by enabling the bitcoin core wallet. As commenting out `disablewallet=1` has not worked, the value is changed in this proposal.

core wallet needs to be enabled to run eps #133

---

raspibolt/raspibolt_faq.md

fix typo in FAQ linux command examples

---

raspibolt/raspibolt_faq.md

Fixed two typos

---

raspibolt/raspibolt_40_lnd.md

Macaroon filepath was referencing the mainnet directory, changed to testnet (lnd/data/chain/bitcoin/testnet/admin.macaroon)
I'm a newbie and this is my first PR. I hope I'm doing this right!

Updated path of macaroon file

---

raspibolt/resources/20-raspibolt-welcome

changed the external HDD section to use a variable that the user can specify at the beginning of the script to make it easier to adapt to different usage scenarios

Edited raspibolt script to use variable for HDD location

---

raspibolt/raspibolt_6A_auto-unlock.md

Added and changed some lines to make the autounlock able to work on LND0.5. I made a pull this pull request on the basis of the proposed adaptations of issue#254 by @zwarbo. I also used a piece of code from the pull request of issue#246 submitted by @martinatime to check for testnet/mainnet.
(I also added the contributers of this commit to the file, as the original writers were mentioned aswell. Not sure if this is ok. )

Updated auto unlock script for LND 0.5

---

raspibolt/resources/20-raspibolt-welcome

updated script to use a user-defined variable for network device name to make it easier for users to adapt the script to wireless or Debian-standard 'predictable network names.'
Changed HDD variable wording for clarity

Added adaptable network device name

---

raspibolt/raspibolt_69_tor.md

I made some changes in the Tor guide as suggested by @bbelo.
I also corrected the incorrect Tor version as signaled by @starkana.

Issue #169: nat=true, Tor version and lnd.conf

---

raspibolt/raspibolt_30_bitcoin.md
thundroid/README.md

These are the necesarry changes for the latest [Bitcoin v0.17.1](https://bitcoincore.org/en/2018/12/25/release-0.17.1/), which has been released today.

Update to Bitcoin 0.17.1

---

raspibolt/raspibolt_20_pi.md

Figured I'd help out and add instructions on adding SSH keys for Mac and Linux users (in response to #316 ).  
I've got one reservation (that I've highlighted in comment), and wouldn't mind hearing opinions on it.

Update raspibolt_20_pi.md with ssh instructions.

---

raspibolt/raspibolt_20_pi.md

Add keepass hyperlink

---

raspibolt/raspibolt_61_system-overview.md

Minimal but worthy changes to make instructions easier to follow.

System overview fix

---

raspibolt/raspibolt_68_shango.md

Update raspibolt_68_shango.md 

---

thundroid/README.md

Fix dead links & remove 1 sentence. ;)

fix dead links

---

raspibolt/raspibolt_40_lnd.md

Just 2 white spaces to make a new line. Nothing Fancy  ¯\_(ツ)_/¯

2 Whitespaces to make new line

---

raspibolt_30_bitcoin.md

Upgrade to Bitcoin Core v0.18.0

---

raspibolt_68_shango.md

Addresses issue https://github.com/Stadicus/RaspiBolt/issues/461

update shango qr code generation

---

raspibolt_20_pi.md
raspibolt_69_tor.md

There are no Stretch in given Raspbian download link anymore.

Update Raspbian from Stretch to Buster

---

raspibolt_30_bitcoin.md

You might also want to update the screenshot...

Update for Bitcoin 0.18.1

---

raspibolt_10_preparations.md

Changed the Bitcoin version to download on your windows machine to version 0.18.0

0.18.0 housekeeping (windows installer)

---

raspibolt_69_tor.md

I see no point in not doing that.
https://github.com/lightningnetwork/lnd/blob/master/docs/configuring_tor.md#tor-stream-isolation

Enable Tor stream isolation for LND

---

raspibolt_30_bitcoin.md
raspibolt_40_lnd.md

Update instructions for bitcoind 0.19.0.1 and LND 0.8.1

Version updates

---

raspibolt_20_pi.md

sudo added to command "adduser bitcoin"

missing sudo added

---

raspibolt_20_pi.md
raspibolt_21_security.md
raspibolt_30_bitcoin.md
raspibolt_40_lnd.md

Minor fixes regarding
* a misleading UFW comment
* using symlinks for Bitcoin and LND permissions for user "admin"
required for https://github.com/Stadicus/RaspiBolt/pull/505

202001 minor fixes

---

raspibolt_61_system-overview.md
resources/20-raspibolt-welcome

The motd script now shows version info and had re-added support for earn.com since my router did not support nat loopback as used in the previous version of the script.

Version info and earn.com support

---

raspibolt_40_lnd.md

Updated the instructions to LND 0.9.0

Update LND 0.9.0

---

raspibolt_6B_btc_rpc_explorer.md

* fix local Electrs connection
* minor wording

BTC RPC Explorer: minor fixes

---

raspibolt_70_troubleshooting.md
raspibolt_faq.md

I updated the doc to mention Raspberry Pi version 4. And I fixed one heading.

Bump Raspberry version

---

raspibolt_50_electrs.md
raspibolt_6B_btc_rpc_explorer.md

Minor fixes of  BTC RPC Explorer instructions.

Clean BTC RPC Explorer instructions

---

raspibolt_30_bitcoin.md
raspibolt_40_lnd.md

I updated LND en BTC to their newest versions.

Updated LND en BTC

---

raspibolt_20_pi.md
raspibolt_40_lnd.md
raspibolt_faq.md

Fix some urls, add a link to Lightning Network resources by Jameson Lopp.

Fix some urls

---

index.md

Add missing links, remove an invalid link.

Fix links on intro page

---

raspibolt_60_bonus.md

Tested this with RaspiBolt v1 on RPi 3, changed `/mnt/hdd` to `/mnt/ext` afterwards. Let me know if something else needs to be changed!
Closes #503.

Add link to JoinMarket guide for RaspiBolt

---

raspibolt_10_preparations.md
raspibolt_30_bitcoin.md

There is a very good guide from Luke-Jr about GPG and signature verification: https://medium.com/@lukedashjr/how-to-securely-install-bitcoin-9bfeca7d3b2a
I believe it is worth mentioning in the doc.

Link signature verification guide

---

raspibolt_64_electrum.md

Download release version 0.2.0 in place of 0.1.7, and update of command to complete the rescan

Update raspibolt_64_electrum.md for EPS v0.2.0

---

raspibolt_30_bitcoin.md

Release notes:
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.20.0.md

bitcoind: update to v0.20.0

---

raspibolt_40_lnd.md

LND 0.10.1 is out!
Contains no major new features but a series of bug fixes.

Update to LND 0.10.1

---

raspibolt_20_pi.md
raspibolt_30_bitcoin.md
raspibolt_69_tor.md

You start "bitcoind" again, not stop it

Start not stop

---

raspibolt_30_bitcoin.md

Bitcoin Core 0.20.1 was released
https://bitcoincore.org/bin/bitcoin-core-0.20.1/

upgrade to Bitcoin Core version v0.20.1

---

raspibolt_faq.md

I added a code snippet to the update LND, specifically after the "remove old stuff" portion of the FAQ for releases after LND 0.5. Personally, I had to search around to make sure I deleted the right stuff. Hopefully this makes it more clear and easy to update LND

LND Update - remove old stuff bullet

---

resources/20-raspibolt-welcome

Fix https://github.com/Stadicus/RaspiBolt/issues/663#issue-751544237

Fix installed electrs version request in raspibolt welcome script

---

raspibolt_40_lnd.md

wget -o specifies the logfile, not the output file

Use -O for output file for wget

---

raspibolt_77_upgrade-external-drive.md

This provides a guide that is useful for anyone wanting/needing to upgrade the existing external hard drive to a newer one.

Add raspibolt_77_upgrade-external-drive.md to Bonus Section

---

raspibolt_20_pi.md

Fixes #675 (Raspi-Config outdated navigation)

Update raspibolt_20_pi.md (Raspi-Config)

---

lnd.md

This change updates LND to the latest official release, known to contain 
improvements due to breaking changes in v0.14.0

LND: update to version 0.14.1

---

btcrpcexplorer.md
electrs.md
rtl.md

Open only tcp ports in ufw, not both tcp/udp

---

lnd.md

Fixing one small typo in a version output
To avoid possible confusion by new users
Fixed version typo
N/A

Fix small typo in LND version output

---

bonus/raspberry-pi/boot-from-microsd-card.md

replaced /mnt/extnew with /data
just a typo...

Fixed typo in /etc/fstab

---

bonus/bitcoin/white-paper.md

A small PR to fix a few typos and to update the headings according to the recommendations in the initial PR review.
To fix typos and to get more meaningful structure (headings)
Followed initial PR review
Test: just checking that the typos are fixed and headings are ok..

White paper bonus guide: Fix a few typos & update headings

---

system-configuration.md

* Update the guide text to reflect the entered command.

Update the guide text to reflect the entered command

---

bonus/raspberry-pi/boot-from-microsd-card.md

For make the directory immutable, the command parameter is : +i and not +1.

Fix cmd in doc

---

electrs.md

Update the Electrs install guide to latest version 0.9.4
* Keep the guide up-to-date
Update `electrs.md`
Test: Check that all required changes to v0.9.4 have been made.

Update Electrs to v0.9.4

---

lnd.md

Update LND from v0.14.1 to v0.14.2 in doc

UPDATE LND : v0.14.1 -> v0.14.2

---

bitcoin-core.md
system-configuration.md

Must be sudo to chown to bitcoin
The current guide doesn't work
Sudo before chown
Fixes #908

Sudo for chown

---

static-channel-backup.md

Hey! I have tried to update these links. Please review my PR.
If any changes still needed do inform me I will update that.
Thanks!

[BUG] Guide: Update the outdated  Link #915

---

mobile-app.md
rtl.md

* Fixes a broken link in the RTL "Next" button at the bottom
* Fixes left menu bar title error ("Web app" instead of "Mobile app")

Two small bug fixes for Zeus

---

resources/20-raspibolt-welcome

Add RTL status in system overview
RTL is standard part in raspibolt v3
Change the original system overview script
Someone needs to adapt the render output section. I don't know how to do it properly.
For the moment, you only have a new line at the end but without version color etc :(
- [ X] independent bonus guide

System overview with RTL

---

guide/bonus/lightning/charge-lnd.md

Fix issue w. charge-lnd is not installed to .local/bin

Added path to install

---

guide/bonus/lightning/balance-of-satoshis.md

patch: bos TG first setup via proxy
fix: some typos

patch: bos TG first setup via proxy

---

resources/20-raspibolt-welcome

Solution of issue #979
It's nice if the correct LND version is displayed on the welcome screen.
I query the currently installed LND version with the command "lncli getinfo" instead of the command "lncli -version".
- [ X] simple bug fix
Fixes #979  (link issue)
As user admin:
$ raspibold
My first pull request :-)

System overview: 

---

guide/bonus/bitcoin/mempool.md

add-on: create and expose a tor hidden service for mempool app
user requested add-on: #996 
Fixes #996

mempool: add Tor hidden service

---

guide/bonus/bitcoin/mempool.md

Just a small formatting fix for mempool guide.

small formatting fix: mempool tor hidden service

---

guide/bitcoin/bitcoin-client.md

Updates Bitcoin Core guide to v23.0. Tested on my node.
There are no breaking changes in this update: https://github.com/lightningnetwork/lnd/releases/tag/v0.14.3-beta
> This release includes new features, various bug fixes and performance improvements, as well as updated translations.
Also, slightly modified the instructions to check the signatures of the manifest file as there was confusion due to all signatures in the list not being good.
Fixes #1004 
Check that all necessary changes have been made

Updates Bitcoin Core guide to v23.0

---

guide/bitcoin/electrum-server.md

Bumped electrs version numbers to v0.9.8

Electrs version bump (v0.9.8)

---

guide/bonus/lightning/cln.md

Update CLN to v0.11.1 (important bugfix) and bugfix paths of set aliases.
Version update which fixes occasional channel closures.
Fixes  #1022

CLN: update to v0.11.1 & bugfix paths of aliases

---

guide/bonus/raspberry-pi/aliases.md
resources/.bash_aliases

I realized was wrong information in the download aliases command and I had the idea to add a new command to show the aliases list directly in the terminal
This can lead to significant improvements to the correct running of the Raspibolt nodes.
- Fixed command to overwrite
- Updated redaction accordingly to change
- Added additional command to display current aliases list directly in the terminal

[UPDATE BONUS GUIDE] Update aliases bonus guide (minor fixes)

---

guide/bonus/bitcoin/joinmarket.md

See https://github.com/raspibolt/raspibolt/pull/1085#issuecomment-1260002075.

Fix JoinMarket guide location in menu

---

guide/bonus/raspberry-pi/command-line.md

Made a few simple updates and tested for compatibility with v3.
- Swapped cd /home/admin/download for cd /tmp/
- Minor text updates
- Confirmed testing complete and status updated
Having a go at contributing

V3 testing complete - Pimp the command line

---

guide/bonus/lightning/lnbits.md

Improvements to the LNBits bonus guide
This can lead to significant improvements to the correct running of the Raspibolt nodes.
- Bump to the latest v 0.9.4 release
- Fix the wrong configuration Tor hidden service (Not necessary SSL connection) [BTC RPC Explorer guide](https://raspibolt.org/guide/bitcoin/blockchain-explorer.html#remote-access-over-tor-optional) as a reference, and added a comment to the hidden service to standardize with the rest of the guide
Open issue #1101

[UPDATE BONUS GUIDE] Update LNBits bonus guide

---

guide/bonus/lightning/index.md
guide/bonus/lightning/regolancer.md

A guide to installing and initially configuring regolancer as a rebalance tool for LND-based nodes.
Regolancer is a new but promising tool that has recently grown in popularity. The tool is CLI based but easy to use once the initial setup is done. Flexible in terms of configurations which allows the noderunner to easily achieve better rebalancing results.
n/a
Fixes # n/a
Follow the instructions and run the rebalancer.
n/a

[NEW BONUS GUIDE] regolancer

---

guide/bitcoin/desktop-wallet.md

Minor fix of link related to Electrum Wallet Desktop update previously merged and some format fixes
- Changed the redirect link to Electrum Wallet Desktop bonus guide
- Added extra lines to format according to Markdown syntax

[UPDATE] Minor fixes on Desktop Wallet guide

---

guide/bitcoin/blockchain-explorer.md

Added comment identifier of the related hidden service
This can lead to significant improvements to the Raspibolt nodes.
- Added hidden service comment to standardize with the rest of the guide
I tested all and is working fine for me

[UPDATE CORE GUIDE] Minor addition in the BTC RPC Explorer guide (Tor hidden service)

---

guide/bonus/lightning/regolancer.md

* This update introduces the option to verify the installed [version](https://github.com/rkfg/regolancer/releases/tag/v1.6.2) of the app and mentions the newly introduced parameter for [rapid rebalance](https://github.com/rkfg/regolancer/releases/tag/v1.6.0).
* Installation steps updated to current version - v1.6.3
Improved functionalities in the app that are helping the installation steps.
Improved documentation.
n/a
n/a

[BONUS GUIDE UPDATE] Regolancer - Version and Rapid rebalance

---

guide/bitcoin/electrum-server.md
guide/bonus/bitcoin/fulcrum.md
guide/bonus/lightning/balance-of-satoshis.md
guide/bonus/raspberry-pi/command-line.md
guide/bonus/raspberry-pi/homer.md

This PR includes various minor fixes of typos and broken links. I also added a step to install bash completion for bitcoind as it might be useful.

Various minor fixes

---

guide/bonus/lightning/ambossping.md

Fix of alignment issues.
improvement
n/a
n/a
n/a

[BONUS GUIDE UPDATE] AmbossPing text in sections TestRun and Error logs alignment

---

guide/bonus/lightning/index.md

Adds missing LNDg entry in bonus guide index

Add missing LNDg entry in bonus guides index

---

guide/bonus/lightning/lndg.md

* Removed bash scripts ([unnecessary](https://t.me/c/1442363505/33440))
* Improved and harmonized the systemd service and timer unit files
* Improved the comments to explain what we do
Simpler section and more meaningful options and comments
For existing LNDg users.
* edit the existing systemd timers and services using the new content
* `sudo systemd daemon-reload`
* `sudo systemctl restart jobs-lndg.timer rebalancer-lndg.timer htlc-stream-lndg.service`
* check the logs and the web GUI to verify that everything is running fine

New LNDg backend scripts section

---

guide/lightning/web-app.md

Updating RTL to latest version 0.13.2 and generalizing update section using `$latest` variable.
Keeping RTL up to date. Latest changes:
- User customizable grids enabling you to control, number of rows on the page, columns you want to view and default sorting order
- Setting to control opening of unannounced channels by default
- Generate Taproot address to receive Bitcoin on-chain (LND only)
- Option to generate AMP invoice (LND only)
Pure Magic

[UPDATE GUIDE] RTL - Update to v0.13.2

---

guide/bitcoin/bitcoin-client.md
guide/bonus/bitcoin/joinmarket.md
guide/lightning/lightning-client.md

Same as closed PR #1087 
Fixes #1043 
Follow new sections: 
- Install ots client
- Check latest LND checksum file timestamp

Install OTS & add timestamp check for LND and JoinMarket

---

guide/lightning/lightning-client.md

Keeping LND updated: v0.15.5 released Dec, 1st 2022
Updating existing guide (lightning-client.md)

[UPDATE BONUS GUIDE] lnd-v0.15.5

---

guide/bonus/lightning/lndg.md

Minor fix of the initial commit section where visualization was broken due to missing tag.
Minor improvement
n/a
n/a
n/a

[UPDATE BONUS GUIDE] LNDg - minor fix

---

guide/bonus/bitcoin/Jam.md

Follow-up on #1185. See title.

JoinMarket webui (Jam) guide nits (formatting)

---

guide/bonus/bitcoin/i2p.md

Improvement of I2P connection of Raspibolt nodes
This can lead to significant improvements in the correct running of the Raspibolt nodes.
- Added standardized structure
- Restructured steps to clarify the guide

[UPDATE BONUS GUIDE] Improved I2P bonus guide, standardizing the format and restructuring steps to clarify the guide

---

guide/bonus/bitcoin/sparrow-terminal.md

Add steps for user to mix using Sparrow Terminal
Improvement of the guide as general. Adding a important and requested feature
Adding following steps
Following the guide and reporting errors, adding steps if necessary

[UPDATE BONUS GUIDE] Sparrow Terminal: Add mixing section

---

guide/bitcoin/bitcoin-client.md
guide/raspberry-pi/system-configuration.md

Adaptation to the new Signature verification process for Bitcoin Core 🔑 – Based the on Guix attestation method to release new Bitcoin Core releases with Bitcoin Core developer's signatures
GitHub repo of Bitcoin Core release attestations (Guix): https://github.com/bitcoin-core/guix.sigs
History:
PR that caused the broke and obsolescence of the old signature verification process: https://github.com/bitcoin/bitcoin/pull/26598
New GitHub folder of the Bitcoin Core repo that stores the signatures now: https://github.com/bitcoin-core/guix.sigs/tree/main/builder-keys
Bitcoin Core's new signature verification method broke the old process, fixed to continue working 
- Added new signature check process
- Adjust of inital dependencies 
Fixes #1230
All tested and worked for me
Thanks to @gzuuus for …

[UPDATE MAIN GUIDE] Update with fixing signature check Bitcoin Core + dependencies update

---

guide/bonus/bitcoin/joinmarket.md

New version of JoinMarket available. Updated to latest version and added $VERSION variable. Minor corrections.
Simplify future maintenance, bring up to date with latest release. Minor bug fixes and suggested updates from user.
Quick replacement of old version throughout using `$ VERSION="0.9.9"`. Reduced the number of future updates to 2 instances (variable assignment and signature verification).
Can easily be tested with a fresh installation of JoinMarket or upgrade to existing installation.
Look ma'

[UPDATE BONUS GUIDE] Update joinmarket.md

---

guide/bonus/lightning/tunnelsats.md

We updated and enhanced the nftable ruleset in TunnelSats scripts, so this should be reflected in RaspiBolt guide as well.
Also TunnelSats repo moved to an organizational github account. Links were corrected.

[bonus guide update] TunnelSats: updated nftables ruleset & links

---

guide/bitcoin/electrum-server.md

Minor updates for latest version v0.9.12. Incorporated VERSION variable help with future maintenance and consistency throughout guides.
Keep the guides up to date.
- Define VERSION variable 
- Replaced version number with $VERSION where applicable
- Manually change other locations where previous version number was referenced
Test via upgrade or new installation. No ongoing maintenance, other then versioning.

[UPDATE MAIN GUIDE] Update Electrum Server section (electrs version)

---

guide/bonus/lightning/cln.md

Update of c-lightning-rest interface to version 0.10.1. 
Local test of c-lightning-rest v0.10.1 installation guide w/ RTL v0.13.3.
Locally tested on amd64 bolt setup w/ CLN 22.11.1 and RTL v0.13.3
CLN 22.11.1 should ideally be merged first ( PR #1210 )
Fixes #1241

[bonus guide update] c-lightning-rest v0.10.1

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.16.2.
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.16.2.md)).

Update LND guide to v0.16.2

---

guide/bonus/lightning/lnbits.md

This PR updates LNbits bonus guide:
- updates lnbits version: 0.10
- changes installation method: venv -> poetry w/ dependencies etc.
- fixes uninstall steps
Keeping up with latest developments around LNbits. Deprecation of venv installation method.
Baseline docs:
- https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md#option-1-recommended-poetry
- https://github.com/raspibolt/raspibolt/pull/1163
Fixes #1250
Pinging lnbits masters around github: @mutatrum @Mynima @TrezorHannes

[UPDATED BONUS GUIDE] LNbits 0.10.5

---

guide/bonus/lightning/lntop.md

current command does not remove lntop
sudo is missing

Update lntop.md fix uninstall

---

guide/bonus/lightning/lnbits.md

Minor version update for LNbits
New version available
Reivew/update bonus guide.
Test by upgrading.

[UPDATE BONUS GUIDE] Update LNbits (versioning)

---

guide/bonus/lightning/lndg.md

- update to latest version of LNDg: v1.6.4
- update from previous versions require special steps described in the update section.
- clarifies and describes user switching when creating data dir for lndg and moving its sqlite db
Fixes #1263

[UPDATE BONUS GUIDE] LNDg - v1.6.4

---

guide/bitcoin/electrum-server.md

Updating Electrs guide to v0.9.14
New version available ([release notes](https://github.com/romanz/electrs/releases))
Reivew/update main guide.
Tested by upgrading.

[UPDATE GUIDE] Update Electrs (versioning)

---

guide/bitcoin/desktop-wallet.md

Typo
The command is not working and for newbies can be confusing
Just a typo. Removed ' at the end of line
Nothinh apply here
Add some snazz if you feel like it :) AHhahahahahahahahahha crazy!

Just a typo

---

guide/lightning/lightning-client.md

Updating LND guide to v0.16.4
new version available with bug fix ([release notes](https://github.com/lightningnetwork/lnd/releases))
Reivew/update main guide.
Tested by upgrading.
Update identified via GitLurker https://www.gitlurker.info/

[UPDATE GUIDE] Update LND (versioning)

---

guide/bonus/lightning/cln.md

Small bugfix PR that removes spacing lines in CLN's config file. Spaces seem to cause trouble.
Bugfix of CLN bonus guide.

[BUGFIX] CLN: remove spaces in config file

---

guide/bonus/lightning/balance-of-satoshis.md
guide/bonus/lightning/lntop.md

make version handling easier
make easier version handling
for new users and updates

Update balance of satoshis

---

guide/bonus/lightning/lndg.md

This PR updates LNDg bonus guide to latest version v1.7.1.
Keeping it updated and enjoying new feature set.
Following install/update instructions of lndg's github repo: https://github.com/cryptosharks131/lndg#manual-installation
Fixes #1315 
Fixes #1317

[UPDATE BONUS GUIDE] LNDg - v1.7.1

---

guide/lightning/web-app.md

Minor change to update RTL to latest version v0.14.0.
This change is required for the upcoming bonus guide update CLN & cln-rest to their latest versions.
Update w.r.t. RTL upgrade section.

[UPDATE GUIDE] web-app: updating RTL v0.14.0

---

guide/lightning/web-app.md

Update RTL to latest version v0.14.1.
https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.14.1

Update Ride The Lightning to v0.14.1

---

guide/bonus/bitcoin/sparrow-terminal.md

Updating Sparrow CLI bonus guide to v1.7.8
new version available with bug fix ([release notes](https://github.com/sparrowwallet/sparrow/releases))
Review/update bonus guide.
Tested by upgrading.
Update identified via GitLurker https://www.gitlurker.info/

[UPDATE BONUS GUIDE] Update Sparrow CLI (versioning)

---

guide/bonus/bitcoin/fulcrum.md

Updates Fulcrum guide to newly released v1.9.6 and rebuilt checks according to the dev method changes
Keeping up with the latest developments and improvements (see [release notes](https://github.com/cculianu/Fulcrum/releases/tag/v1.9.6)).
- Updated commands associated with the new signatures & check method

[UPDATE] Bump version Fulcrum and rebuilt checks according to dev changes

---

guide/lightning/web-app.md

This small PR fixes enumeration and formatting of NodeJS installation part in RTL's installation guide. 
Styleguide

web-app: fix enumeration and formatting

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.17.2
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/v0.17.2-beta/docs/release-notes/release-notes-0.17.2.md))

[UPDATE] Bump LND to v0.17.2

---

guide/lightning/lightning-client.md

Updates LND guide to newly released v0.17.3
Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/v0.17.3-beta/docs/release-notes/release-notes-0.17.3.md))

[UPDATE] Bump LND to v0.17.3

---

guide/bonus/raspberry-pi/command-line.md

Update bash completion to the latest changes and other improvements
Keep the guide updated
- Updated download URLs to the new PATH
- Changed format to standardize with the rest of the guide
- Changed a command to improve the result
Tested for me and working fine ✅

[UPDATE] Bash completion

---

guide/bitcoin/blockchain-explorer.md

Update blockchain-explorer.md - simple guide typo fix

---

guide/bonus/bitcoin/joinmarket.md

1) There is formatting error for my key.
2) Releases are not always signed by Adam Gibson now.

Trivial fixes in JoinMarket bonus guide

---

guide/bonus/bitcoin/joinmarket.md

Update to newest version. There are various performance improvements, bugfixes and adds new features to RPC API which will be needed for the next release of Jam.
Also removed `--linenumbers` from configuration section, as they change from version to version.

Update JoinMarket to v0.9.11

---

guide/bonus/bitcoin/safu-ninja.md
index.md

Fix broken links.
These were found with [link-inspector](https://github.com/justindhillon/link-inspector).

Fix broken links

---

guide/bonus/lightning/balance-of-satoshis.md

Fix for typo on "developer" in docs

Fix typo in balance of satoshis

---

guide/bonus/bitcoin/dojo.md
guide/bonus/lightning/balance-of-satoshis.md
resources/UTXOracle.py

fix some typos in comment
make comment more clearly

chore: fix some typos in comment

---

resources/UTXOracle.py

Update UTXOracle to newest version.
https://x.com/SteveSimple/status/1889325264808677668
Original file - https://utxo.live/oracle/UTXOracle.py.

Update UTXOracle to version 8
